{
 "title": "Infra Overview",
 "description": "FX Infrastructure Overview",
 "tags": [
  "FX",
  "INFRA",
  "Overview",
  "HOME"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_VMETRICS", "label": "DS (Metrics)", "query": "prometheus" },
   {
    "name": "DS_VLOGS",
    "label": "DS (Logs)",
    "query": "victoriametrics-logs-datasource"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Infrastructure",
   "type": "table",
   "description": "All infra components and links",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max by (ip,instance) (up{job=\"traefik_metrics\"})"
    },
    {
     "expr": "max by (ip,instance) (grafana_build_info{job=\"grafana_metrics\"})"
    },
    {
     "expr": "max by (ip,instance) (vm_app_version{job=\"vmetrics_metrics\"})"
    },
    {
     "expr": "max by (ip,instance) (vm_app_version{job=\"vlogs_metrics\"})"
    },
    {
     "expr": "max by (ip,instance) (vm_app_version{job=\"vtraces_metrics\"})"
    },
    {
     "expr": "max by (ip,instance) (vm_app_version{job=\"vmalert_metrics\"})"
    },
    {
     "expr": "max by (ip,instance) (alertmanager_build_info{job=\"alertmanager_metrics\"})"
    },
    {
     "expr": "max by (ip,instance) (node_exporter_build_info{job=\"node_exporters\"})"
    }
   ]
  },
  {
   "title": "Infrastructure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 14, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "nomad" },
    { "expr": "1", "legendFormat": "consul" },
    { "expr": "1", "legendFormat": "traefik" },
    { "expr": "1", "legendFormat": "grafana" },
    { "expr": "1", "legendFormat": "vmetrics" },
    { "expr": "1", "legendFormat": "vlogs" },
    { "expr": "1", "legendFormat": "vtraces" },
    { "expr": "1", "legendFormat": "vmalert" },
    { "expr": "1", "legendFormat": "alertmanager" },
    { "expr": "1", "legendFormat": "cadvisor" },
    { "expr": "1", "legendFormat": "vector" },
    { "expr": "1", "legendFormat": "minio" },
    { "expr": "1", "legendFormat": "loki" }
   ]
  },
  {
   "title": "Aliveness",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 14, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (instance) (up{job=\"traefik_metrics\"})",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "max by (instance) (up{job=\"grafana_metrics\"})",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "max by (instance) (up{job=\"vmetrics_metrics\"})",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "max by (instance) (up{job=\"vlogs_metrics\"})",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "max by (instance) (up{job=\"vtraces_metrics\"})",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "max by (instance) (up{job=\"vmalert_metrics\"})",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "max by (instance) (up{job=\"alertmanager_metrics\"})",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "max by (instance) (up{job=\"minio_metrics\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 10, "w": 5, "x": 19, "y": 7 } },
  {
   "title": "Infra Aliveness",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "up{job=~\"alertmanager_metrics|grafana_metrics|minio_metrics|vector_metrics|vlogs_metrics|vmalert_metrics|vmetrics_metrics\"}",
     "legendFormat": "{{ job }} @ {{ instance }}"
    }
   ]
  },
  {
   "title": "ALERT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(ALERTS{alertstate=\"firing\", job=~\"infra|etcd\"}) or on() vector(0)",
       "legendFormat": "Firing Alert"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 3, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count(ALERTS{alertstate=\"firing\", job=~\"infra|etcd\"}) by (alertname, severity)",
       "legendFormat": "{{ alertname }}"
      }
     ]
    },
    {
     "title": "Firing Alerts",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum without (instance,instance,datname) (ALERTS{alertstate=\"firing\", job=~\"infra|etcd\"})",
       "legendFormat": "[{{ severity }}] {{alertname}} @ {{ job }}"
      }
     ]
    },
    { "title": "Grafana Alerts", "type": "alertlist", "gridPos": { "h": 16, "w": 5, "x": 19, "y": 18 } },
    {
     "title": "Active Alerts",
     "type": "table",
     "gridPos": { "h": 9, "w": 19, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "ALERTS{job=~\"infra|etcd\"}"
      }
     ]
    }
   ]
  },
  { "title": "TRAEFIK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Traefik Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "nomad_job_name:traefik | stats count() as count",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Traefik Requests by Status",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nomad_job_name:traefik DownstreamStatus:~\"^2..\" | stats by (host) count() as count",
     "legendFormat": "{{ host }} 2xx"
    },
    {
     "expr": "nomad_job_name:traefik DownstreamStatus:~\"^3..\" | stats by (host) count() as count",
     "legendFormat": "{{ host }} 3xx"
    },
    {
     "expr": "nomad_job_name:traefik DownstreamStatus:~\"^4..\" | stats by (host) count() as count",
     "legendFormat": "{{ host }} 4xx"
    },
    {
     "expr": "nomad_job_name:traefik DownstreamStatus:~\"^5..\" | stats by (host) count() as count",
     "legendFormat": "{{ host }} 5xx"
    }
   ]
  },
  {
   "title": "Traefik Request Duration (ns)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nomad_job_name:traefik | stats by (host) avg(Duration) as avg_ns",
     "legendFormat": "{{ host }} avg"
    },
    {
     "expr": "nomad_job_name:traefik | stats by (host) quantile(0.95, Duration) as p95_ns",
     "legendFormat": "{{ host }} p95"
    }
   ]
  },
  { "title": "Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(up{job=~\"alertmanager_metrics|grafana_metrics|vlogs_metrics|vmalert_metrics|vmetrics_metrics\"}) by (ip)",
     "legendFormat": "infra @ {{ ip }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "vCore" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=~\"alertmanager_metrics|grafana_metrics|vlogs_metrics|vmalert_metrics|vmetrics_metrics\"}[1m])) by (ip)",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=~\"alertmanager_metrics|grafana_metrics|vlogs_metrics|vmalert_metrics|vmetrics_metrics\"}) by (ip)",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_data_size_bytes{job=\"vmetrics_metrics\"}) by (ip)\n+ sum(vl_data_size_bytes{job=\"vlogs_metrics\"}) by (ip)\n+ sum(vt_data_size_bytes{job=\"vtraces_metrics\"}) by (ip)",
     "legendFormat": "Storage"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vm_data_size_bytes{job=\"vmetrics_metrics\"}[1m])) by (ip)\n+ sum(rate(vl_data_size_bytes{job=\"vlogs_metrics\"}[1m])) by (ip)\n+ sum(rate(vt_data_size_bytes{job=\"vtraces_metrics\"}[1m])) by (ip)",
     "legendFormat": "Data Rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(go_threads{job=~\"alertmanager_metrics|grafana_metrics|vlogs_metrics|vmalert_metrics|vmetrics_metrics\"}) by (ip)",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_open_fds{job=~\"alertmanager_metrics|grafana_metrics|vlogs_metrics|vmalert_metrics|vmetrics_metrics\"}) by (ip)",
     "legendFormat": "OpenFDs"
    }
   ]
  },
  { "title": "Grafana", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "grafana_build_info{job=\"grafana_metrics\"}",
     "legendFormat": "{{ job }} @ {{ instance }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"grafana_metrics\"}",
     "legendFormat": "{{ instance }} uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(grafana_http_request_duration_seconds_count{job=\"grafana_metrics\"}[1m])) by (instance)",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, \n  sum(rate(grafana_http_request_duration_seconds_bucket[5m])) by (instance,le)\n)",
     "legendFormat": "RT P50"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "c" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(grafana_database_conn_open{job=\"grafana_metrics\"}) by (instance)",
     "legendFormat": "DB Conn"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"grafana_metrics\"}) by (instance)",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"grafana_metrics\"}[1m])",
     "legendFormat": "CPU"
    }
   ]
  },
  { "title": "Victoria Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vm_app_version{job=\"vmetrics_metrics\"}",
     "legendFormat": "{{ job }} @ {{ instance }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"vmetrics_metrics\"}",
     "legendFormat": "{{ instance }} uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_cache_entries{job=\"vmetrics_metrics\",type=\"storage/hour_metric_ids\"}) by (instance)",
     "legendFormat": "Series"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(vm_rows_inserted_total{job=\"vmetrics_metrics\"}[1m]))",
     "legendFormat": "Sample / s"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_promscrape_targets{job=\"vmetrics_metrics\"}) by (instance)",
     "legendFormat": "Targets"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"vmetrics_metrics\"}) by (instance)",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vm_data_size_bytes{job=\"vmetrics_metrics\"}) by (instance)",
     "legendFormat": "Storage"
    }
   ]
  },
  { "title": "Victoria Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vm_app_version{job=\"vlogs_metrics\"}",
     "legendFormat": "{{ job }} @ {{ instance }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"vlogs_metrics\"}",
     "legendFormat": "{{ instance }} Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Total lines of log stored",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vl_storage_rows{job=\"vlogs_metrics\"}) by (instance)",
     "legendFormat": "Lines"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vl_rows_ingested_total{job=\"vlogs_metrics\"}[1m])) by (instance)",
     "legendFormat": "Lines / s"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vl_rows_dropped_total{job=\"vlogs_metrics\"}[5m])) by (instance)",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"vlogs_metrics\"}) by (instance)",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vl_data_size_bytes{job=\"vlogs_metrics\"}) by (instance)",
     "legendFormat": "Storage"
    }
   ]
  },
  { "title": "Victoria Traces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vm_app_version{job=\"vtraces_metrics\"}",
     "legendFormat": "{{ job }} @ {{ instance }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"vtraces_metrics\"}",
     "legendFormat": "{{ instance }} uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vt_rows_dropped_total{job=\"vtraces_metrics\"}[1m])) by (instance)",
     "legendFormat": "Dropped / s"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vt_storage_rows{job=\"vtraces_metrics\"}) by (instance)",
     "legendFormat": "Rows"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "stream/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vt_streams_created_total{job=\"vtraces_metrics\"}[5m])) by (instance)",
     "legendFormat": "Streams"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"vtraces_metrics\"}) by (instance)",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vt_data_size_bytes{job=\"vtraces_metrics\"}) by (instance)",
     "legendFormat": "Storage"
    }
   ]
  },
  { "title": "Victoria Alert", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vm_app_version{job=\"vmalert_metrics\"}",
     "legendFormat": "{{ job }} @ {{ instance }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"vmalert_metrics\"}",
     "legendFormat": "{{ instance }} uptime"
    }
   ]
  },
  {
   "type": "stat",
   "description": "eval rules per second",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vmalert_iteration_total[1m])) by (instance)",
     "legendFormat": "Eval Rate"
    }
   ]
  },
  {
   "type": "stat",
   "description": "5m alert sending",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(vmalert_alerts_sent_total{job=\"vmalert_metrics\"}[5m])) by (instance)\n",
     "legendFormat": "Alert 5m"
    }
   ]
  },
  {
   "type": "stat",
   "description": "5m alert sending",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(vmalert_iteration_missed_total{job=\"vmalert_metrics\"}[5m])) by (instance)",
     "legendFormat": "Missed"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"vmalert_metrics\"}) by (instance)",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rate(process_cpu_seconds_total{job=\"vmalert_metrics\"}[1m])) by (instance)",
     "legendFormat": "CPU"
    }
   ]
  },
  { "title": "AlertManager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "alertmanager_build_info{job=\"alertmanager_metrics\"}",
     "legendFormat": "{{ job }} @ {{ instance }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"alertmanager_metrics\"}",
     "legendFormat": "{{ instance }} Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(alertmanager_notifications_total{job=\"alertmanager_metrics\"}[5m])) by (instance)",
     "legendFormat": "Received 5m"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(alertmanager_notifications_failed_total{job=\"alertmanager_metrics\"}[5m])) by (instance)",
     "legendFormat": "Failed 5m"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(alertmanager_silences{job=\"alertmanager_metrics\",state=\"active\"}) by (instance)",
     "legendFormat": "Silences"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"alertmanager_metrics\"}) by (instance)",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"alertmanager_metrics\"}[1m])",
     "legendFormat": "CPU"
    }
   ]
  },
  { "title": "MinIO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_software_version_info{job=\"minio_metrics\"}",
     "legendFormat": "{{ job }} @ {{ instance }} v{{ version }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_node_process_uptime_seconds{job=\"minio_metrics\"}",
     "legendFormat": "{{ instance }} Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minio_cluster_capacity_usable_total_bytes{job=\"minio_metrics\"}) by (instance)",
     "legendFormat": "Usable"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minio_cluster_capacity_usable_free_bytes{job=\"minio_metrics\"}) by (instance)",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minio_cluster_usage_object_total{job=\"minio_metrics\"}) by (instance)",
     "legendFormat": "Objects"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(minio_s3_requests_total{job=\"minio_metrics\"}[1m])) by (instance)",
     "legendFormat": "Req / s"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(minio_cluster_drive_online_total{job=\"minio_metrics\"}) by (instance)",
     "legendFormat": "Drives Online"
    }
   ]
  },
  { "title": "Vector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"vector_metrics\"}",
     "legendFormat": "{{ job }} @ {{ instance }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vector_uptime_seconds{job=\"vector_metrics\"}",
     "legendFormat": "{{ instance }} Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vector_component_sent_events_total{job=\"vector_metrics\"}[1m])) by (instance)",
     "legendFormat": "Events / s"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vector_http_client_errors_total{job=\"vector_metrics\"}[1m])) by (instance)",
     "legendFormat": "Errors / s"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(vector_component_received_bytes_total{job=\"vector_metrics\"}[1m])) by (instance)",
     "legendFormat": "Bytes In / s"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(vector_buffer_byte_size{job=\"vector_metrics\"}) by (instance)",
     "legendFormat": "Buffer Mem"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(vector_utilization{job=\"vector_metrics\"}) by (instance)",
     "legendFormat": "Utilization"
    }
   ]
  }
 ]
}