{
 "title": "Logs Instance",
 "description": "Logs for Single Node/Instance",
 "tags": [
  "FX",
  "INFRA",
  "Instance",
  "NODE"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "DS_VLOGS",
    "label": "DS (Logs)",
    "query": "victoriametrics-logs-datasource"
   },
   { "name": "instance", "label": "Host", "query": { "query": "" } },
   { "name": "job", "label": "Service", "query": { "query": "" } },
   { "name": "search", "label": "Search" }
  ]
 },
 "panels": [
  {
   "title": "Logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "host:$instance service_name:$job | stats by (host,service_name) count() as count",
     "legendFormat": "{{ host }}.{{ service_name }}"
    }
   ]
  },
  {
   "title": "Searched Logs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "host:$instance service_name:$job $search | stats by (host,service_name) count() as count",
     "legendFormat": "{{ host }}.{{ service_name }}"
    }
   ]
  },
  {
   "title": "Raw Logs",
   "type": "logs",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "host:$instance service_name:$job $search "
    }
   ]
  }
 ]
}