{
 "title": "Node Overview",
 "description": "Node Home Dashboard",
 "tags": [
  "FX",
  "NODE",
  "Overview",
  "HOME"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_VMETRICS", "label": "DS (Metrics)", "query": "prometheus" },
   { "name": "job", "label": "Environment", "query": { "query": "label_values(node_load1, job)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_load1{job=\"$job\"}) by (ip))",
     "legendFormat": "Node"
    },
    {
     "expr": "sum by (job) (count without (cpu)(node_cpu_seconds_total{job=\"$job\",mode=\"idle\"}))",
     "legendFormat": "Core"
    },
    {
     "expr": "sum by (job) (node_memory_MemTotal_bytes{job=\"$job\"})",
     "legendFormat": "Mem"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{job=\"$job\",fstype!~\"(n|root|tmp)fs.*\"})",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (1 - rate(node_cpu_seconds_total{job=\"$job\",mode=\"idle\"}[1m])) / sum by (job) (count without (cpu)(node_cpu_seconds_total{job=\"$job\",mode=\"idle\"}))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (node_load1{job=\"$job\"}) / sum by (job) (count without (cpu)(node_cpu_seconds_total{job=\"$job\",mode=\"idle\"}))",
     "legendFormat": "Load"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - sum by (job) (node_memory_MemAvailable_bytes{job=\"$job\"}) / sum by (job) (node_memory_MemTotal_bytes{job=\"$job\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - sum by (job) (node_filesystem_avail_bytes{job=\"$job\",fstype!~\"(n|root|tmp)fs.*\"}) / sum by (job) (node_filesystem_size_bytes{job=\"$job\",fstype!~\"(n|root|tmp)fs.*\"})",
     "legendFormat": "Space"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 17, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (cluster, job) (1 - rate(node_cpu_seconds_total{mode=\"idle\"}[1m]))",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Yellow : Node\n\nGreen: HAProxy\n\nRed: Vector Logging Agent\n\nGreen: Docker\n\nPurple: Keepalived",
   "gridPos": { "h": 17, "w": 16, "x": 8, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node_exporters\"}",
     "legendFormat": "{{ instance }}"
    },
    { "expr": "vector(0)", "legendFormat": "{{ instance }}" },
    {
     "expr": "vector_up{job=\"node\"}",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "up{job=\"juice\"}",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "docker_up{job=\"node\"}",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "min by (job,cluster,vip) (probe_success{job=\"node-vip\"})",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", job=\"$job\"}) or on() vector(0)",
     "legendFormat": "Firing Alert"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", job=\"$job\"}) by (alertname, severity)",
     "legendFormat": "{{ alertname }}"
    }
   ]
  },
  {
   "title": "Firing Alerts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\", job=\"$job\"}",
     "legendFormat": "[{{ severity }}] {{alertname}} @ {{ instance }} @ {{ instance }}"
    }
   ]
  },
  {
   "title": "Members",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "panels": [
    {
     "title": "All Nodes",
     "type": "table",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "up{job=\"node_exporters\"}"
      },
      {
       "expr": "group without(instance,cluster,instance) (node_uname_info{})"
      },
      {
       "expr": "max by (ip) (avg by (ip,instance,job) (1 - rate(node_cpu_seconds_total{mode=\"idle\"}[1m])))"
      },
      {
       "expr": "max by (ip) (1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)"
      },
      {
       "expr": "sum by (ip,instance) (max by (ip,instance) (1 - node_filesystem_avail_bytes{fstype!~\"(n|root|tmp)fs.*\"} / node_filesystem_size_bytes{fstype!~\"(n|root|tmp)fs.*\"}))"
      },
      {
       "expr": "max by (ip) (count without (cpu)(node_cpu_seconds_total{mode=\"idle\"})) "
      },
      {
       "expr": "max by (ip) (node_memory_MemTotal_bytes{}) / 1073741824"
      },
      {
       "expr": "sum(node_filesystem_size_bytes{fstype!~\"(n|root|tmp)fs.*\"}) by (ip) / 1073741824"
      },
      { "expr": "count by (ip) (up{ip!=''})" },
      {
       "expr": "max by (ip) (probe_duration_seconds{job=\"ping\"})"
      },
      { "expr": "vector(0)" },
      {
       "expr": "min by (ip) (up{job=\"node_exporters\"})"
      },
      {
       "expr": "min by (ip) (node_timex_sync_status{})"
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "panels": [
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg by (instance, job) (avg_over_time(1 - rate(node_cpu_seconds_total{job=\"$job\",mode=\"idle\"}[1m])[1m:]))",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Load 15",
     "type": "timeseries",
     "description": "Standard node load in last 15 minutes (divide by cpu core number)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg_over_time((node_load15{job=\"$job\"} / on(instance,job) group_left() count without (cpu)(node_cpu_seconds_total{job=\"$job\",mode=\"idle\"}))[1m:])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "description": "Memory usage ratio for each nodes:\n(total - avail) / total",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "1 - node_memory_MemAvailable_bytes{job=\"$job\"} / node_memory_MemTotal_bytes{job=\"$job\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Disk I/O RT (1m)",
     "type": "timeseries",
     "description": "Disk Read/Write Time Total / Disk IOPS in last minute",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(rate(node_disk_read_time_seconds_total[1m]) + rate(node_disk_write_time_seconds_total[1m])) / (rate(node_disk_reads_completed_total[1m]) + rate(node_disk_writes_completed_total[1m]))",
       "legendFormat": "{{ instance }}-{{ device }}"
      }
     ]
    },
    {
     "title": "Disk IO Bandwidth",
     "type": "timeseries",
     "description": "total disk bandwidth per node",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (instance,job) (rate(node_disk_read_bytes_total{job=\"$job\"}[1m]) + rate(node_disk_written_bytes_total{job=\"$job\"}[1m]))",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Network IO Rate1m",
     "type": "timeseries",
     "description": "total network bandwidth (tx+rx) per node in last 1 minute",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum by (instance,job) (rate(node_network_receive_bytes_total{job=\"$job\",device!~\"lo|bond.*\"}[1m]) + rate(node_network_transmit_bytes_total{job=\"$job\",device!~\"lo|bond.*\"}[1m]))",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Space Usage",
     "type": "stat",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "1 - node_filesystem_avail_bytes{job=\"$job\",fstype!~\"(n|root|tmp)fs.*\"} / node_filesystem_size_bytes{job=\"$job\",fstype!~\"(n|root|tmp)fs.*\"}",
       "legendFormat": "{{ instance }}:{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "Ping RT",
     "type": "stat",
     "description": "Network RT in µs",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "probe_duration_seconds{job=\"ping\"}",
       "legendFormat": "{{ instance }} @ {{ ip }}"
      },
      {
       "expr": "avg by (job,vip) (probe_duration_seconds{job=~\".*vip\"})",
       "legendFormat": "{{ job }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "panels": [
    {
     "type": "table",
     "description": "HAProxy instances in this deployment, click Admin URL to view more details in haproxy stat page.",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 29 },
     "targets": [
      { "expr": "vector(0)" }
     ]
    },
    {
     "type": "table",
     "description": "Services exposed in this deployment",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 29 },
     "targets": [
      { "expr": "vector(0)" },
      { "expr": "vector(0)" }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "vector(0)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Service Health",
     "type": "state-timeline",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 39 },
     "targets": [
      { "expr": "vector(0)", "legendFormat": "{{ proxy }}" }
     ]
    }
   ]
  }
 ]
}