{
 "title": "Node Disk",
 "description": "Node: Disk Details",
 "tags": [
  "FX",
  "NODE",
  "Instance",
  "Disk"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_VMETRICS", "label": "DS (Metrics)", "query": "prometheus" },
   {
    "name": "id",
    "label": "Node ID",
    "query": {
     "query": "label_values(node_uname_info, instance)"
    }
   },
   {
    "name": "ip",
    "label": "IP Address",
    "query": {
     "query": "label_values(node_uname_info{instance=\"$id\"}, ip)"
    }
   },
   {
    "name": "node",
    "label": "Hostname",
    "query": {
     "query": "label_values(node_uname_info{instance=\"$id\"}, hostname)"
    }
   },
   {
    "name": "ins",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{instance=\"$id\"}, instance)"
    }
   },
   {
    "name": "cls",
    "label": "Cluster",
    "query": {
     "query": "label_values(node_uname_info{instance=\"$id\"}, cluster)"
    }
   },
   {
    "name": "pg_ins",
    "label": "PG Instance",
    "query": {
     "query": "label_values(pg_up{ip=\"$ip\"}, instance)"
    }
   },
   {
    "name": "disk",
    "label": "Disk",
    "query": {
     "query": "label_values(node_disk_reads_completed_total{ip=\"$ip\"},device)"
    }
   },
   {
    "name": "vip",
    "label": "VIP Address",
    "query": {
     "query": "label_values(probe_success{ip=\"$ip\"}, vip)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Disk Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disk iostat",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (device) (irate(node_disk_io_time_seconds_total{ip=\"$ip\"}[1m]))",
     "legendFormat": "util"
    },
    {
     "expr": "max by (device) (irate(node_disk_io_time_weighted_seconds_total{ip=\"$ip\"}[1m]))",
     "legendFormat": "queue"
    },
    {
     "expr": "max by (device) (irate(node_disk_reads_completed_total{ip=\"$ip\"}[1m]))",
     "legendFormat": "r/s"
    },
    {
     "expr": "max by (device) (irate(node_disk_writes_completed_total{ip=\"$ip\"}[1m]))",
     "legendFormat": "w/s"
    },
    {
     "expr": "max by (device) (irate(node_disk_reads_merged_total{ip=\"$ip\"}[1m]))",
     "legendFormat": "mr/s"
    },
    {
     "expr": "max by (device) (irate(node_disk_writes_merged_total{ip=\"$ip\"}[1m]))",
     "legendFormat": "mw/s"
    },
    {
     "expr": "max by (device) (rate(node_disk_read_bytes_total{ip=\"$ip\"}[1m]))",
     "legendFormat": "rb/s"
    },
    {
     "expr": "max by (device) (irate(node_disk_written_bytes_total{ip=\"$ip\"}[1m]))",
     "legendFormat": "wb/s"
    },
    {
     "expr": "max by (device) ((rate(node_disk_read_time_seconds_total{ip=\"$ip\"}[1m]) / rate(node_disk_reads_completed_total{ip=\"$ip\"}[1m])))",
     "legendFormat": "r_await"
    },
    {
     "expr": "max by (device) ((rate(node_disk_write_time_seconds_total{ip=\"$ip\"}[1m]) / rate(node_disk_writes_completed_total{ip=\"$ip\"}[1m])))",
     "legendFormat": "w_await"
    },
    {
     "expr": "max by (device) ((rate(node_disk_read_bytes_total{ip=\"$ip\"}[1m]) / rate(node_disk_reads_completed_total{ip=\"$ip\"}[1m])))",
     "legendFormat": "rreq-sz"
    },
    {
     "expr": "max by (device) ((rate(node_disk_written_bytes_total{ip=\"$ip\"}[1m]) / rate(node_disk_writes_completed_total{ip=\"$ip\"}[1m])))",
     "legendFormat": "wreq-sz"
    }
   ]
  },
  { "title": "Disk Metrics - Basic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Read IOPS",
   "type": "timeseries",
   "description": "Read operations per second (irate1m)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{ip=\"$ip\", device=~'$disk'}[1m])",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "timeseries",
   "description": "Write operations per second (irate1m)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_disk_writes_completed_total{ip=\"$ip\", device=~'$disk'}[1m])",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Read Bandwidth",
   "type": "timeseries",
   "description": "Read Bytes per Second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{ip=\"$ip\", device=~'$disk'}[1m])",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Write Bandwidth",
   "type": "timeseries",
   "description": "Write Bytes per Second",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_disk_written_bytes_total{ip=\"$ip\", device=~'$disk'}[1m])",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Read Response Time",
   "type": "timeseries",
   "description": "Read Response Time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{ip=~\"$ip\", device=~'$disk'}[1m]) /\nirate(node_disk_reads_completed_total{ip=\"$ip\", device=~'$disk'}[1m])",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Write Response Time",
   "type": "timeseries",
   "description": "Write Response Time",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "irate(node_disk_write_time_seconds_total{ip=~\"$ip\", device=~'$disk'}[1m]) /\nirate(node_disk_writes_completed_total{ip=\"$ip\", device=~'$disk'}[1m])",
     "legendFormat": "{{ device }}"
    }
   ]
  },
  {
   "title": "Disk Metrics - Extended",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "panels": [
    {
     "title": "Read Request Size (areq-sz)",
     "type": "timeseries",
     "description": "Average Read Size in Bytes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(node_disk_read_bytes_total{ip=\"$ip\", device=~'$disk'}[15s]) / \nirate(node_disk_reads_completed_total{ip=\"$ip\", device=~'$disk'}[15s])",
       "legendFormat": "{{ device }}"
      }
     ]
    },
    {
     "title": "Write Request Size (areq-sz)",
     "type": "timeseries",
     "description": "Average Write Size in Bytes",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(node_disk_written_bytes_total{ip=\"$ip\", device=~'$disk'}[15s]) / \nirate(node_disk_writes_completed_total{ip=\"$ip\", device=~'$disk'}[15s])",
       "legendFormat": "{{ device }}"
      }
     ]
    },
    {
     "title": "Reads Merged Ratio",
     "type": "timeseries",
     "description": "Merged ratio of read requests",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "irate(node_disk_reads_merged_total{ip=\"$ip\", device=~'$disk'}[1m]) /\n(irate(node_disk_reads_merged_total{ip=\"$ip\", device=~'$disk'}[1m]) +\n irate(node_disk_reads_completed_total{ip=\"$ip\", device=~'$disk'}[1m]))",
       "legendFormat": "{{ device }}"
      }
     ]
    },
    {
     "title": "Write Merged Ratio",
     "type": "timeseries",
     "description": "Merged ratio of write requests",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "irate(node_disk_writes_merged_total{ip=\"$ip\", device=~'$disk'}[1m]) /\n(irate(node_disk_writes_merged_total{ip=\"$ip\", device=~'$disk'}[1m]) +\n irate(node_disk_writes_completed_total{ip=\"$ip\", device=~'$disk'}[1m]))",
       "legendFormat": "{{ device }}"
      }
     ]
    },
    {
     "title": "Instant Queue Size",
     "type": "timeseries",
     "description": "Number of items which were in the queue at the sampling time point",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_disk_io_now{ip=\"$ip\", device=~'$disk'}",
       "legendFormat": "{{ device }}"
      }
     ]
    },
    {
     "title": "Average Queue Size",
     "type": "timeseries",
     "description": "average number of operations waiting to be serviced.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(node_disk_io_time_weighted_seconds_total{ip=\"$ip\", device=~'$disk'}[1m])",
       "legendFormat": "{{ device }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{ip=\"$ip\", fstype!~\"(n|root|tmp)fs.*\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "max by (device) (node_filesystem_avail_bytes{ip=\"$ip\", fstype!~\"(n|root|tmp)fs.*\"})",
       "legendFormat": "Avail"
      },
      {
       "expr": "max by (device) (node_filesystem_size_bytes{ip=\"$ip\", fstype!~\"(n|root|tmp)fs.*\"} - node_filesystem_avail_bytes{ip=\"$ip\", fstype!~\"(n|root|tmp)fs.*\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "max by (device) ((1 - node_filesystem_avail_bytes{ip=\"$ip\", fstype!~\"(n|root|tmp)fs.*\"} / node_filesystem_size_bytes{ip=\"$ip\", fstype!~\"(n|root|tmp)fs.*\"}))",
       "legendFormat": "Usage"
      },
      {
       "expr": "max by (device) (node_filesystem_files{ip=\"$ip\", fstype!~\"(n|root|tmp)fs.*\"})",
       "legendFormat": "iNodes"
      },
      {
       "expr": "max by (device) (node_filesystem_files_free{ip=\"$ip\", fstype!~\"(n|root|tmp)fs.*\"})",
       "legendFormat": "iNode Free"
      },
      {
       "expr": "max by (device) ((node_filesystem_files{ip=\"$ip\", fstype!~\"(n|root|tmp)fs.*\"} - node_filesystem_files_free{ip=\"$ip\", fstype!~\"(n|root|tmp)fs.*\"}))",
       "legendFormat": "iNode Used"
      },
      {
       "expr": "max by (device) ((1 - node_filesystem_files_free{ip=\"$ip\", fstype!~\"(n|root|tmp)fs.*\"} / node_filesystem_files{ip=\"$ip\", fstype!~\"(n|root|tmp)fs.*\"}))",
       "legendFormat": "iNode Usage"
      },
      {
       "expr": "min by (device) (node_filesystem_readonly{ip=\"$ip\", fstype!~\"(n|root|tmp)fs.*\"})",
       "legendFormat": "iNode Usage"
      }
     ]
    },
    {
     "title": "Space Usage",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1 - node_filesystem_avail_bytes{ip=\"$ip\", fstype!~\"(n|root|tmp)fs.*\"} / node_filesystem_size_bytes{ip=\"$ip\", fstype!~\"(n|root|tmp)fs.*\"})",
       "legendFormat": "{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "Avail Space 1D Prediction",
     "type": "stat",
     "description": "Prediction of avail filesystem space a day later!",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "predict_linear(node_filesystem_avail_bytes{ip=\"$ip\", fstype!~\"(n|root|tmp)fs.*\"}[1h], 86400)",
       "legendFormat": "{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "iNode Usage",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1 - node_filesystem_files_free{ip=\"$ip\", fstype!~\"(n|root|tmp)fs.*\"} / node_filesystem_files{ip=\"$ip\", fstype!~\"(n|root|tmp)fs.*\"})",
       "legendFormat": "{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "Device Error",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_filesystem_device_error{ip=\"$ip\", fstype!~\"(n|root|tmp)fs.*\"}",
       "legendFormat": "{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "Space Derive 1h",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "deriv(node_filesystem_avail_bytes{ip=\"$ip\", fstype!~\"(n|root|tmp)fs.*\"}[1h])",
       "legendFormat": "{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "Space Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(1 - node_filesystem_avail_bytes{ip=\"$ip\", fstype!~\"(n|root|tmp)fs.*\"} / node_filesystem_size_bytes{ip=\"$ip\", fstype!~\"(n|root|tmp)fs.*\"})",
       "legendFormat": "{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "Space Exhaust Estimate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg_over_time((clamp(node_filesystem_avail_bytes{ip=\"$ip\", fstype!~\"(n|root|tmp)fs.*\"} / -deriv(node_filesystem_avail_bytes{ip=\"$ip\", fstype!~\"(n|root|tmp)fs.*\"}[1h]), -1, 126230400))[5m:1m])",
       "legendFormat": "{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "FD Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_filefd_allocated{ip=\"$ip\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "(node_filefd_allocated{ip=\"$ip\"} / node_filefd_maximum{ip=\"$ip\"})",
       "legendFormat": "Usage"
      }
     ]
    }
   ]
  }
 ]
}