{
 "title": "PGSQL Cluster",
 "description": "PostgreSQL Cluster Dashboard",
 "tags": [
  "FX",
  "PGSQL",
  "Cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "DS_VLOGS",
    "label": "DS (Logs)",
    "query": "victoriametrics-logs-datasource"
   },
   { "name": "DS_VMETRICS", "label": "DS (Metrics)", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(pg_up, cluster)" } },
   {
    "name": "primary",
    "label": "Primary",
    "query": {
     "query": "label_values(pg:cluster:leader{cluster=\"$cluster\"}, instance)"
    }
   },
   {
    "name": "members",
    "label": "Primary",
    "query": {
     "query": "label_values(pg_up{cluster=\"$cluster\"}, ip)"
    }
   },
   {
    "name": "node_cls",
    "label": "Node Cluster",
    "query": {
     "query": "label_values(node_load1{ip=~\"$members\"},cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_meta_info{instance=\"$primary\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Cluster",
        "type": "string",
        "values": [ "${cluster}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    }
   ]
  },
  {
   "type": "table",
   "description": "All instances among pgsql cluster ${cluster}\n\nInstance: Goto PGSQL Instance\n\nIP: Goto PGSQL Node\n\nStatus: Goto PGSQL Service\n\nLoad: max(cpu,postgres,pgbouncer)\n\nSpace: Disk space usage max(all device)\n\nProxy: session number, Goto Haproxy Admin Page",
   "gridPos": { "h": 6, "w": 11, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "min by (instance,ip) (up{job=\"pgsql\", cluster=\"$cluster\"})"
    },
    {
     "expr": "max by (instance) (pg:instance:load1{cluster=\"$cluster\"})"
    },
    {
     "expr": "sum by (instance) (pg:instance:xact_total_rate1m{cluster=\"$cluster\"})"
    },
    {
     "expr": "min by (instance,ip) (pg_in_recovery{cluster=\"$cluster\"})"
    },
    {
     "expr": "max by (instance) (pg:instance:num_backends{cluster=\"$cluster\"})"
    },
    { "expr": "vector(0)" }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "max by (datname) (pg_db_datid{cluster=\"$cluster\"})",
     "legendFormat": "OID"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pg_up{cluster=\"$cluster\"})",
     "legendFormat": "Instance"
    },
    { "expr": "vector(0)", "legendFormat": "Service" },
    {
     "expr": "count(max by (cluster,datname) (pg_db_age{cluster=\"$cluster\"}))",
     "legendFormat": "Database"
    },
    {
     "expr": "count(group by (instance) (pg_db_numbackends{cluster='$cluster'}))",
     "legendFormat": "Proxy"
    },
    {
     "expr": "count(count by (ip) (pg_up{cluster=\"$cluster\"}))",
     "legendFormat": "Node"
    },
    {
     "expr": "sum(pg:cluster:cpu_count{cluster=\"$cluster\"})",
     "legendFormat": "Core"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{ip=~\"$members\"})",
     "legendFormat": "Mem"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{ip=~\"$members\",mountpoint=\"/\"})",
     "legendFormat": "Disk"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Blue = PostgreSQL\n\nGreen = Pgbouncer\n\nYellow = Agent (Patroni / PG Exporters)",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": " sum by (cluster) (pg_up{cluster=\"$cluster\"})",
     "legendFormat": "postgres"
    },
    {
     "expr": " sum by (cluster) (pgbouncer_up{cluster=\"$cluster\"})",
     "legendFormat": "pgbouncer"
    },
    { "expr": "vector(0)", "legendFormat": "patroni" },
    {
     "expr": " sum by (cluster) (pg_exporter_agent_up{cluster=\"$cluster\"})",
     "legendFormat": "pg_exporter"
    },
    {
     "expr": " sum by (cluster) (pgbouncer_exporter_agent_up{cluster=\"$cluster\"})",
     "legendFormat": "pgb_exporter"
    },
    {
     "expr": " sum by (cluster) (pgbackrest_exporter_agent_up{cluster=\"$cluster\"})",
     "legendFormat": "pgbackrest"
    },
    {
     "expr": " sum(node_up{ip=~\"$members\"})",
     "legendFormat": "node"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Ping RT",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (job,vip) (probe_duration_seconds{ip=~\"$members\", job=~\".*vip\"})",
     "legendFormat": "{{ vip }} @ {{ job }}"
    },
    {
     "expr": "probe_duration_seconds{ip=~\"$members\", job=\"ping\"}",
     "legendFormat": "{{ ip }} : {{ instance }}"
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 7 },
   "targets": [
    { "expr": "vector(0)", "legendFormat": "{{ proxy }}" }
   ]
  },
  {
   "title": "Postgres",
   "type": "stat",
   "description": "Instances among this cluster and their saturation (postgres or pgbouncer)",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg:instance:load1{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Node",
   "type": "stat",
   "description": "Node of this cluster and their cpu usage.",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node:instance:cpu_usage_1m{ip=~\"$members\"}",
     "legendFormat": "{{ ip }}"
    }
   ]
  },
  {
   "title": "Proxy",
   "type": "stat",
   "description": "Proxy backend session number among this cluster",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "conn" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "vector(0)", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Component",
   "type": "stat",
   "description": "Load of different compoents.",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:cluster:load1{cluster=\"$cluster\"}",
     "legendFormat": "Postgres"
    },
    {
     "expr": "pgbouncer:cluster:load1{cluster=\"$cluster\"}",
     "legendFormat": "Pgbouncer"
    },
    {
     "expr": "sum(rate(process_cpu_seconds_total{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "Exporter"
    },
    { "expr": "vector(0)", "legendFormat": "Haproxy" },
    {
     "expr": "pg:cluster:cpu_usage{cluster=\"$cluster\"}",
     "legendFormat": "Node"
    }
   ]
  },
  {
   "title": "Service",
   "type": "stat",
   "description": "Registered service among this cluster.\n\nClick goes to PGSQL Service Dashboard",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "c" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "vector(0)", "legendFormat": "{{ proxy }}" }
   ]
  },
  {
   "title": "Database",
   "type": "stat",
   "description": "TPS of each database",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_db_xact_total{cluster=\"$cluster\", datname!~'template\\\\d'}[1m]))",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pg_db_xact_commit{cluster=\"$cluster\"}[1m]))\n# pg:cluster:xact_commit_rate1m{cluster=\"$cluster\"}",
     "legendFormat": "Commit"
    },
    {
     "expr": "sum(rate(pg_db_xact_rollback{cluster=\"$cluster\"}[1m]))\n# pg:cluster:xact_commit_rate1m{cluster=\"$cluster\"}",
     "legendFormat": "Rollback"
    },
    {
     "expr": "sum(rate(pgbouncer_stat_total_xact_count{cluster=\"$cluster\"}[1m])) \n# pgbouncer:cluster:xact_rate1m{cluster=\"$cluster\"} ",
     "legendFormat": "TPS"
    },
    {
     "expr": "sum(rate(pgbouncer_stat_total_query_count{cluster=\"$cluster\"}[1m])) \n# pgbouncer:cluster:query_rate1m{cluster=\"$cluster\"} ",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) (pg_db_numbackends{cluster=\"$cluster\"})",
     "legendFormat": "Backend"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) (pgbouncer_pool_waiting_clients{cluster=\"$cluster\"})\n# pgbouncer:cluster:waiting_clients{cluster=\"$cluster\"}",
     "legendFormat": "Queue"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(pgbouncer_stat_total_query_time{cluster=\"$cluster\"}[1m])) / sum(rate(pgbouncer_stat_total_query_count{cluster=\"$cluster\"}[1m]))\n# pgbouncer:cluster:query_rt_1m{cluster=\"$cluster\"}",
     "legendFormat": "Cluster RT"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(pgbouncer_stat_total_query_time{cluster=\"$cluster\", instance=\"$primary\"}[1m])) / sum(rate(pgbouncer_stat_total_query_count{cluster=\"$cluster\", instance=\"$primary\"}[1m]))\n# pgbouncer:instance:query_rt_1m{instance=\"$primary\"}",
     "legendFormat": "Primary RT"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(pg_replication_lag_seconds{cluster=\"$cluster\"}) or vector(0)",
     "legendFormat": "Lag (s)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(pg_flush_lsn{cluster=\"$cluster\"} - pg_replay_lsn{cluster=\"$cluster\"}) or vector(0)",
     "legendFormat": "Lag (B)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max by (cluster) (pg_db_age{cluster=\"$cluster\", datname!~\"template[0-9]\"})  / 2147483647\n# pg:cluster:age{cluster=\"$cluster\"} / 2147483647",
     "legendFormat": "Age"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(node:fs:space_usage{ip=~\"$members\"})",
     "legendFormat": "Space"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Overall pressure for this PostgreSQL Node and Instance. \nmax(node:instance:cpu_usage, pg:instance:load, pgbouncer:instance:load)",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:cluster:load1{cluster=\"$cluster\"}",
     "legendFormat": "cluster"
    },
    {
     "expr": "pg:instance:load1{cluster=\"$cluster\", instance=\"$primary\"}",
     "legendFormat": "{{ instance }} ⭐️"
    },
    {
     "expr": "pg:instance:load1{cluster=\"$cluster\", instance!=\"$primary\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Alerting event graph. Each stripe represents an alerting event. Gray transparent stripes are pending alerts.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ALERTS{cluster=\"$cluster\", alertstate=\"firing\"}",
     "legendFormat": "[{{ severity }}🔥] {{alertname}} @ {{ instance }}"
    },
    { "expr": "0", "legendFormat": "Alert" }
   ]
  },
  { "title": "Leadership", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg:cluster:leader{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Leadership",
   "type": "timeseries",
   "description": "Leadership shows who is in charge of this cluster ${cluster}",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(pg_in_recovery{cluster=\"$cluster\"} == 0) * 0 + 1",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Timeline",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_timeline_id{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Traffic Routes (primary service instance)",
   "type": "timeseries",
   "description": "Haproxy will route $cluster-primary traffic to which instance ?",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "vector(0)",
     "legendFormat": "$cluster-primary ➔ {{ server }}"
    }
   ]
  },
  { "title": "Member", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_meta_info{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "type": "table",
   "description": "All nodes among cluster ${cluster}",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "node_up{ip=~\"$members\"}"
    },
    {
     "expr": "group without(instance,cluster,instance) (node_uname_info{ip=~\"$members\"})"
    },
    {
     "expr": "max by (ip) (node:instance:cpu_usage_1m{ip=~\"$members\"})"
    },
    {
     "expr": "max by (ip) ((1 - node_memory_MemAvailable_bytes{ip=~\"$members\"} / node_memory_MemTotal_bytes{ip=~\"$members\"}))"
    },
    {
     "expr": "max by (ip,instance) (node:fs:space_usage{ip=~\"$members\"})"
    },
    {
     "expr": "max by (ip) (node:instance:cpu_count{ip=~\"$members\"}) "
    },
    {
     "expr": "max by (ip) (node_memory_MemTotal_bytes{ip=~\"$members\"}) / 1073741824"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{ip=~\"$members\",mountpoint=\"/\"}) by (ip) / 1073741824"
    },
    {
     "expr": "count by (ip) (up{ip=~\"$members\"})"
    },
    {
     "expr": "max by (ip) (probe_duration_seconds{ip=~\"$members\", job=\"ping\"})"
    },
    { "expr": "vector(0)" },
    {
     "expr": "min by (ip) (node_up{ip=~\"$members\"})"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Blue = PostgreSQL\n\nGreen = Pgbouncer\n\nYellow = Agent (Patroni / PG Exporters)",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_up{ip=~\"$members\"}",
     "legendFormat": "postgres {{ instance }}"
    },
    {
     "expr": "pgbouncer_up{ip=~\"$members\"}",
     "legendFormat": "pgbouncer {{ instance }}"
    },
    { "expr": "vector(0)", "legendFormat": "patroni {{ instance }}" },
    {
     "expr": "pg_exporter_agent_up{ip=~\"$members\"}",
     "legendFormat": "pg_exporter {{ instance }}"
    },
    {
     "expr": "pgbouncer_exporter_agent_up{ip=~\"$members\"}",
     "legendFormat": "pgb_exporter {{ instance }}"
    },
    {
     "expr": "pgbackrest_exporter_agent_up{ip=~\"$members\"}",
     "legendFormat": "pgbackrest {{ instance }}"
    },
    {
     "expr": "node_up{ip=~\"$members\"}",
     "legendFormat": "node {{ instance }}"
    },
    { "expr": "vector(0)", "legendFormat": "haproxy {{ instance }}" },
    {
     "expr": "docker_up{ip=~\"$members\"}",
     "legendFormat": "docker {{ instance }}"
    },
    {
     "expr": "vector_up{ip=~\"$members\"}",
     "legendFormat": "vector {{ instance }}"
    },
    {
     "expr": "max by (instance) (up{job=\"juice\", ip=~\"$members\"})",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "max by (instance) (up{cluster=\"nginx\", ip=~\"$members\"})",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "max by (instance) (up{cluster=\"grafana\", ip=~\"$members\"})",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "max by (instance) (up{cluster=\"vmetrics\", ip=~\"$members\"})",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "max by (instance) (up{cluster=\"vlogs\", ip=~\"$members\"})",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "max by (instance) (up{cluster=\"vtraces\", ip=~\"$members\"})",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "max by (instance) (up{cluster=\"vmalert\", ip=~\"$members\"})",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "max by (instance) (up{cluster=\"alertmanager\", ip=~\"$members\"})",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "etcd_up{ip=~\"$members\"}",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "redis_up{ip=~\"$members\"}",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "minio_up{ip=~\"$members\"}",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "mongo_up{ip=~\"$members\"}",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "mysql_up{ip=~\"$members\"}",
     "legendFormat": "mysql {{ instance }}"
    },
    {
     "expr": "mysql_exporter_up{ip=~\"$members\"}",
     "legendFormat": "mysql_exporter"
    }
   ]
  },
  {
   "title": "Patroni Members",
   "type": "table",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 44 },
   "targets": [
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Postgres Instances",
   "type": "table",
   "description": "All instances among pgsql cluster ${cluster}\n\nInstance: Goto PGSQL Instance\n\nIP: Goto PGSQL Node\n\nStatus: Goto PGSQL Service\n\nLoad: max(cpu,postgres,pgbouncer)\n\nSpace: Disk space usage max(all device)\n\nProxy: session number, Goto Haproxy Admin Page",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "pg_in_recovery{cluster=\"$cluster\"}"
    },
    {
     "expr": "min by (instance,ip) (up{cluster=\"$cluster\", job=\"pgsql\"})"
    },
    {
     "expr": "instance:pressure1{cluster=\"$cluster\"}"
    },
    {
     "expr": "sum by (instance) (pg:instance:xact_total_rate1m{cluster=\"$cluster\"})"
    },
    {
     "expr": "max by (instance) (pg:instance:num_backends{cluster=\"$cluster\"})"
    },
    {
     "expr": "max by (instance) (pgbouncer:instance:xact_rt_1m{cluster=\"$cluster\"})"
    },
    {
     "expr": "max by (instance) (pg:instance:conn_usage{cluster=\"$cluster\"})"
    },
    {
     "expr": "sum by (instance) (pgbouncer:instance:query_rate1m{cluster=\"$cluster\"})"
    },
    {
     "expr": "sum by (instance) (pgbouncer:instance:waiting_clients{cluster=\"$cluster\"})"
    },
    {
     "expr": "max by (instance) (pg:instance:lag_bytes{cluster=\"$cluster\", instance=~'$cluster.*'})"
    }
   ]
  },
  {
   "title": "Settings",
   "type": "table",
   "description": "Important configuration entries of this instance",
   "gridPos": { "h": 13, "w": 5, "x": 19, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "pg_meta_info{instance=\"$primary\"}"
    }
   ]
  },
  {
   "title": "Database",
   "type": "table",
   "description": "Database of this cluster ${cluster}\n\nLoad: active_time / backends (PG14 only)\n\nQuery RT : max query rt of this database\n\nClient: Pgbouncer Active Clients\n\nServer: Pgbouncer Active Servers\n\nBackend: Postgres num backends\n\nT = is Template?\n\nD = Disabled in Pgbouncer ?\n\nP = Paused in Pgbouncer ?",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum by (datname) (pg_size_bytes{cluster=\"$cluster\", datname!~\"wal|log\"})",
     "legendFormat": "Size"
    },
    {
     "expr": "max by (datname) (pg:db:age{cluster=\"$cluster\"})",
     "legendFormat": "Age"
    },
    {
     "expr": "max by (datname) (pg_db_is_template{cluster=\"$cluster\", instance=\"$primary\"})",
     "legendFormat": "isTemplate"
    },
    {
     "expr": "sum by (datname) (pg_activity_count{cluster=\"$cluster\"})",
     "legendFormat": "Backend"
    },
    {
     "expr": "sum by (datname) (pg:db:xact_commit_rate1m{cluster=\"$cluster\"})",
     "legendFormat": "TPS"
    },
    {
     "expr": "max by (datname) (pg_db_conn_limit{instance=\"$primary\"})",
     "legendFormat": "Conn Limit"
    },
    {
     "expr": "max by (datname) (pgbouncer:db:query_rt_1m{instance=\"$primary\"})",
     "legendFormat": "RT"
    },
    {
     "expr": "max by (datname) (pg:db:conn_usage{cluster=\"$cluster\"})",
     "legendFormat": "PG Conn Usage"
    },
    {
     "expr": "max by (datname) (pgbouncer_database_disabled{instance=\"$primary\", datname!=\"pgbouncer\"})",
     "legendFormat": "Disabled"
    },
    {
     "expr": "max by (datname) (pgbouncer_database_paused{instance=\"$primary\", datname!=\"pgbouncer\"})",
     "legendFormat": "Paused"
    },
    {
     "expr": "sum by (datname) (pg:db:active_time_rate1m{cluster=\"$cluster\"}) / sum by (datname) (pg_db_numbackends{cluster=\"$cluster\"})",
     "legendFormat": "Load"
    },
    {
     "expr": "sum by (datname) (pgbouncer:db:active_clients{cluster=\"$cluster\"})",
     "legendFormat": "Client"
    },
    {
     "expr": "sum by (datname) (pgbouncer:db:active_servers{cluster=\"$cluster\"})",
     "legendFormat": "Server"
    },
    {
     "expr": "max by (datname,host) (pgbouncer_database_pool_size{cluster=\"$cluster\", datname!=\"pgbouncer\"} + pgbouncer_database_reserve_pool{cluster=\"$cluster\", datname!=\"pgbouncer\"})",
     "legendFormat": "PoolSize"
    },
    {
     "expr": "max by (datname) (pg_db_datid{cluster=\"$cluster\"})",
     "legendFormat": "OID"
    }
   ]
  },
  {
   "title": "Service",
   "type": "table",
   "description": "Service map tells whether a server can be used as a specific service/role/svc.\ne.g Offline marks this server can be used as offline server",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 63 },
   "targets": [
    { "expr": "vector(0)" }
   ]
  },
  {
   "title": "Proxies",
   "type": "table",
   "description": "All haproxy among this cluster ${cluster}\n\nInstance: Goto PGSQL Instance\n\nIP: Goto PGSQL Node\n\nStatus: Goto PGSQL Service\n\nLoad: max(cpu,postgres,pgbouncer)\n\nSpace: Disk space usage max(all device)\n\nProxy: session number, Goto Haproxy Admin Page",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 63 },
   "targets": [
    { "expr": "vector(0)", "legendFormat": "Service" },
    { "expr": "vector(0)", "legendFormat": "Session" },
    { "expr": "vector(0)", "legendFormat": "Session" }
   ]
  },
  {
   "title": "Replication",
   "type": "table",
   "description": "Replication Status among cluster ${cluster}",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "pg:cluster:sender{cluster=\"$cluster\"}"
    },
    {
     "expr": "pg:cluster:receiver{cluster=\"$cluster\"}"
    }
   ]
  },
  { "title": "Metric", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "Cluster (5m) & Instance (1m) CPU Usage",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:cluster:cpu_usage_5m{cluster=\"$cluster\"}",
     "legendFormat": "cluster"
    },
    {
     "expr": "pg:instance:cpu_usage_1m{cluster=\"$cluster\", instance=\"$primary\"}",
     "legendFormat": "{{ instance }} ⭐️"
    },
    {
     "expr": "pg:instance:cpu_usage_1m{cluster=\"$cluster\", instance!=\"$primary\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Xacts (5m)",
   "type": "timeseries",
   "description": "Total transactions (commit + rollback) per second from PostgreSQL in last 5 minutes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(pg_db_xact_total{cluster=\"$cluster\"}[5m])) \n# pg:cluster:xact_commit_rate1m{cluster=\"$cluster\", instance=\"$primary\"}",
     "legendFormat": "cluster"
    },
    {
     "expr": "sum by (instance) (rate(pg_db_xact_total{cluster=\"$cluster\", instance=\"$primary\"}[5m])) \n# pg:cluster:xact_commit_rate1m{cluster=\"$cluster\", instance=\"$primary\"}",
     "legendFormat": "{{ instance }} ⭐️"
    },
    {
     "expr": "sum by (instance) (rate(pg_db_xact_total{cluster=\"$cluster\", instance!=\"$primary\"}[5m])) \n# pg:cluster:xact_commit_rate1m{cluster=\"$cluster\", instance=\"$primary\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Session",
   "type": "timeseries",
   "description": "Number of backends for each instances among this cluster",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "sum by (instance) (pg_activity_count{cluster=\"$cluster\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CRUD",
   "type": "timeseries",
   "description": "Tuples fetched, inserted, updated, delete among this cluster",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_db_tup_fetched{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "SELECT"
    },
    {
     "expr": "sum(rate(pg_db_tup_inserted{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "INSERTED"
    },
    {
     "expr": "sum(rate(pg_db_tup_updated{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "UPDATED"
    },
    {
     "expr": "sum(rate(pg_db_tup_deleted{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "DELETED"
    }
   ]
  },
  {
   "title": "RT",
   "type": "timeseries",
   "description": "Average transaction response time from pgbouncer\n(You can get from postgres directly after PG14)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg:cluster:active_time_rate1m{cluster=\"$cluster\"} / pg:cluster:xact_total_rate1m{cluster=\"$cluster\"} # PG14",
     "legendFormat": "cluster"
    },
    {
     "expr": "pg:instance:active_time_rate1m{cluster=\"$cluster\", instance=\"$primary\"} / pg:instance:xact_total_rate1m{cluster=\"$cluster\", instance=\"$primary\"} # PG14",
     "legendFormat": "{{ instance }} ⭐️"
    },
    {
     "expr": "pg:instance:active_time_rate1m{cluster=\"$cluster\", instance!=\"$primary\"} / pg:instance:xact_total_rate1m{cluster=\"$cluster\", instance!=\"$primary\"} # PG14",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "timeseries",
   "description": "Replication Lag (WAL Replay Lag) measured in bytes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(pg_flush_lsn{cluster=\"$cluster\"} - pg_replay_lsn{cluster=\"$cluster\"}) or vector(0)",
     "legendFormat": "{{ instance }} → {{ usename }}:{{ appname }}@{{ address }}"
    }
   ]
  },
  {
   "title": "Query Time Spent",
   "type": "timeseries",
   "description": "Time spent per second for each query of each instances.",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pg_query_exec_time{cluster=\"$cluster\"}[1m])",
     "legendFormat": "{{ instance }}-{{ query }}"
    }
   ]
  },
  {
   "title": "XID Usage",
   "type": "stat",
   "description": "Ratio of XID used for each database among this cluster",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (datname) (pg_db_age{cluster=\"$cluster\", datname!~\"template[0-9]\"}) / 2147483647",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Disk / Network",
   "type": "timeseries",
   "description": "R▲ for disk read bandwidth\nTX▲ for network transmit bandwidth\nRX▼ for network receive bandwidth\nW▼ for disk write bandwidth",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "node:instance:disk_read_bytes_rate1m{ip=~\"$members\"} * on(ip) group_right pg_up{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}-R▲"
    },
    {
     "expr": "node:instance:network_tx_bytes_rate1m{ip=~\"$members\"} * on(ip) group_right pg_up{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}-TX▲"
    },
    {
     "expr": "- node:instance:network_rx_bytes_rate1m{ip=~\"$members\"} * on(ip) group_right pg_up{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}-RX▼"
    },
    {
     "expr": "- node:instance:disk_write_bytes_rate1m{ip=~\"$members\"} * on(ip) group_right pg_up{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}-W▼"
    }
   ]
  },
  {
   "title": "Space Usage (Max)",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (mountpoint) (node:fs:space_usage{ip=~\"$members\"})",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 } },
  {
   "title": "Total Logs",
   "type": "stat",
   "description": "Total log events in the current time window",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cluster:$cluster service_name:timescaledb | stats count() as count",
     "legendFormat": "postgres"
    },
    {
     "expr": "cluster:$cluster service_name:pgcat | stats count() as count",
     "legendFormat": "pgbouncer"
    }
   ]
  },
  {
   "title": "PG Logs",
   "type": "timeseries",
   "description": "PGSQL Logs Event",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "cluster:$cluster service_name:timescaledb | stats count() as count",
     "legendFormat": "postgres"
    },
    {
     "expr": "cluster:$cluster\nservice_name:in(\"timescaledb\",\"pgcat\") \n| stats by (service_name) count() as count",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 123 },
   "targets": [
    {
     "expr": "service_name:timescaledb cluster:$cluster \n| fields pg_level, host, _msg",
     "legendFormat": "{{ src }}"
    }
   ]
  },
  {
   "title": "PGSQL syslog",
   "type": "logs",
   "description": "syslog from \"postgres\", \"patroni\", \"pgbouncer\", \"pg_exporter\", \"pgbouncer_exporter\", \"pgbackrest_exporter\", \"vip-manager\"",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 123 },
   "targets": [
    {
     "expr": "cluster:$cluster \nservice_name:in(\"timescaledb\",\"pgcat\") \n| fields level, host, _msg",
     "legendFormat": "{{ src }}"
    }
   ]
  }
 ]
}