{
 "title": "PGSQL Exporter",
 "description": "PostgreSQL Instance Dashboard",
 "tags": [
  "FX",
  "PGSQL",
  "Instance"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_VMETRICS", "label": "DS (Metrics)", "query": "prometheus" },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(pg_up, instance)" } },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(pg_up{instance=\"$instance\"} , ip)"
    }
   },
   {
    "name": "seq",
    "label": "Sequence",
    "query": {
     "query": "label_values(pg_up{instance=\"$instance\"},  instance)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(pg_up{instance=\"$instance\"}, cluster)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{ip=\"$ip\"},nodename)"
    }
   },
   {
    "name": "datname",
    "label": "Database",
    "query": {
     "query": "label_values(pg_db_age{instance=\"$instance\",datname!~'template0|template1'}, datname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Instance",
        "type": "string",
        "values": [ "$instance" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Cluster",
        "type": "string",
        "values": [ "${cluster}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Node IP",
        "type": "string",
        "values": [ "${ip}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Hostname",
        "type": "string",
        "values": [ "${node}" ]
       }
      ],
      "meta": {}
     }
    }
   ]
  },
  {
   "title": "Export Status",
   "type": "table",
   "description": "Exporter Aliveness Status in ${cluster}\n\nInstance: Goto PGSQL Instance\n\nIP: Goto PGSQL Node\n\nStatus: Goto PGSQL Service\n\nLoad: max(cpu,postgres,pgbouncer)\n\nSpace: Disk space usage max(all device)\n\nProxy: session number, Goto Haproxy Admin Page",
   "gridPos": { "h": 6, "w": 10, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "max by (instance) (pg_exporter_agent_up{cluster=\"$cluster\"})"
    },
    {
     "expr": "max by (instance) (pgbouncer_exporter_agent_up{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (instance) (pgbackrest_exporter_agent_up{cluster=\"$cluster\"})"
    },
    {
     "expr": "max by (instance) (pg_exporter_uptime{cluster=\"$cluster\"})"
    },
    {
     "expr": "max by (instance) (pgbouncer_exporter_uptime{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Aliveness",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_exporter_agent_up{instance=\"$instance\"}",
     "legendFormat": "pg_exporter"
    },
    {
     "expr": "pgbouncer_exporter_agent_up{instance=\"$instance\"}",
     "legendFormat": "pgbouncer_exporter"
    },
    {
     "expr": "pg_up{instance=\"$instance\"}",
     "legendFormat": "postgres"
    },
    {
     "expr": "pgbouncer_up{instance=\"$instance\"}",
     "legendFormat": "pgbouncer"
    },
    {
     "expr": "patroni_up{instance=\"$instance\"}",
     "legendFormat": "patroni"
    },
    {
     "expr": "pgbackrest_exporter_agent_up{instance=\"$instance\"}",
     "legendFormat": "pgbackrest_exporter"
    }
   ]
  },
  { "title": "Global Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Aliveness",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "pg_exporter_agent_up{}", "legendFormat": "{{ instance }}" },
    { "expr": "pgbouncer_exporter_agent_up{}", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "type": "table",
   "description": "All instances among pgsql cluster ${cluster}\n\nInstance: Goto PGSQL Instance\n\nIP: Goto PGSQL Node\n\nStatus: Goto PGSQL Service\n\nLoad: max(cpu,postgres,pgbouncer)\n\nSpace: Disk space usage max(all device)\n\nProxy: session number, Goto Haproxy Admin Page",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "max by (instance) (pg_exporter_agent_up{})"
    },
    {
     "expr": "max by (instance) (pgbouncer_exporter_agent_up{})"
    },
    {
     "expr": "max by (instance) (pg_exporter_uptime{})"
    },
    {
     "expr": "max by (instance) (pgbouncer_exporter_uptime{})"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "pg_exporter_scrape_duration{}", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Global Uptime",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "pg_exporter_uptime{}", "legendFormat": "{{ instance }}" },
    { "expr": "pgbouncer_exporter_uptime{}", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Global Error Rate",
   "type": "timeseries",
   "description": "Error Increase in last 1 minute",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(pg_exporter_scrape_error_count{}[1m])",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "increase(pgbouncer_exporter_scrape_error_count{}[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Up Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_exporter_uptime{instance=\"$instance\"}",
     "legendFormat": "postgres"
    },
    {
     "expr": "pgbouncer_exporter_uptime{instance=\"$instance\"}",
     "legendFormat": "pgbouncer"
    }
   ]
  },
  {
   "title": "Exporter Aliveness",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_exporter_agent_up{instance=\"$instance\"}",
     "legendFormat": "postgres"
    },
    {
     "expr": "pgbouncer_exporter_agent_up{instance=\"$instance\"}",
     "legendFormat": "pgbouncer"
    },
    {
     "expr": "pgbackrest_exporter_agent_up{instance=\"$instance\"}",
     "legendFormat": "pgbackrest"
    }
   ]
  },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_exporter_scrape_duration{instance=\"$instance\"}",
     "legendFormat": "postgres"
    },
    {
     "expr": "pgbouncer_exporter_scrape_duration{instance=\"$instance\"}",
     "legendFormat": "pgbouncer"
    }
   ]
  },
  {
   "title": "Errors Count Per Minute",
   "type": "timeseries",
   "description": "Error Increase in last 1 minute",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(pg_exporter_scrape_error_count{instance=\"$instance\"}[1m])",
     "legendFormat": "postgres"
    },
    {
     "expr": "increase(pgbouncer_exporter_scrape_error_count{instance=\"$instance\"}[1m])",
     "legendFormat": "pgbouncer"
    }
   ]
  },
  {
   "title": "Scrape Duration (per Server)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_exporter_server_scrape_duration{instance=\"$instance\"}",
     "legendFormat": "{{ datname }}"
    },
    {
     "expr": "pgbouncer_exporter_server_scrape_duration{instance=\"$instance\"}",
     "legendFormat": "pgbouncer"
    }
   ]
  },
  {
   "title": "Scrape Count Per Minute",
   "type": "timeseries",
   "description": "Scrape Count",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(pg_exporter_server_scrape_total_count{instance=\"$instance\"}[1m])",
     "legendFormat": "{{ datname }}"
    },
    {
     "expr": "increase(pgbouncer_exporter_server_scrape_total_count{instance=\"$instance\"}[1m])",
     "legendFormat": "pgbouncer"
    }
   ]
  },
  { "title": "Collectors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Query Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (query) (increase(pg_exporter_query_scrape_error_count{instance=\"$instance\"}[1m]))",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "Metrics Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (query) (pg_exporter_query_scrape_metric_count{instance=\"$instance\"})",
     "legendFormat": "{{query}}"
    },
    {
     "expr": "sum by (query) (pgbouncer_exporter_query_scrape_metric_count{instance=\"$instance\"})",
     "legendFormat": "{{query}}"
    }
   ]
  },
  {
   "title": "Query Duration",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(pg_exporter_query_scrape_duration{instance=\"$instance\"}[1m]) / \nincrease(pg_exporter_query_scrape_total_count{instance=\"$instance\"}[1m])",
     "legendFormat": "{{ datname }}.{{ query }}"
    },
    {
     "expr": "increase(pgbouncer_exporter_query_scrape_duration{instance=\"$instance\"}[1m]) / \nincrease(pgbouncer_exporter_query_scrape_total_count{instance=\"$instance\"}[1m])",
     "legendFormat": "pgbouncer.{{ query }}"
    }
   ]
  },
  {
   "title": "Query Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(pg_exporter_query_scrape_hit_count{instance=\"$instance\"}[5m]) / \nincrease(pg_exporter_query_scrape_total_count{instance=\"$instance\"}[5m])",
     "legendFormat": "{{ datname }}.{{query}}"
    },
    {
     "expr": "increase(pgbouncer_exporter_query_scrape_hit_count{instance=\"$instance\"}[5m]) / \nincrease(pgbouncer_exporter_query_scrape_total_count{instance=\"$instance\"}[5m])",
     "legendFormat": "{{ datname }}.{{query}}"
    }
   ]
  },
  {
   "title": "Cache TTL",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_exporter_query_cache_ttl{instance=\"$instance\"}",
     "legendFormat": "{{ datname }}.{{ query }}"
    },
    {
     "expr": "pgbouncer_exporter_query_cache_ttl{instance=\"$instance\"}",
     "legendFormat": "pgbouncer. {{ query }}"
    }
   ]
  }
 ]
}