{
 "title": "PGSQL Activity",
 "description": "PostgreSQL Queries for single Instance",
 "tags": [
  "FX",
  "PGSQL",
  "Cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_VMETRICS", "label": "DS (Metrics)", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(pg_up, cluster)" } },
   {
    "name": "primary",
    "label": "Primary",
    "query": {
     "query": "label_values(pg:cluster:leader{cluster=\"$cluster\"}, instance)"
    }
   },
   {
    "name": "members",
    "label": "Primary",
    "query": {
     "query": "label_values(pg_up{cluster=\"$cluster\"}, ip)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Cluster",
        "type": "string",
        "values": [ "${cluster}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Leader",
        "type": "string",
        "values": [ "$primary" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 16, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by (entrypoint) (traefik_open_connections{entrypoint!~\"traefik|metrics\"}) > bool 0",
     "legendFormat": "{{ entrypoint }}"
    }
   ]
  },
  { "title": "Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Postgres Load 1m",
   "type": "timeseries",
   "description": "Overall pressure for this PostgreSQL Node and Instance. \nmax(node:instance:cpu_usage, pg:instance:load, pgbouncer:instance:load)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:cluster:load1{cluster=\"$cluster\"}",
     "legendFormat": "cluster"
    },
    {
     "expr": "pg:instance:load1{cluster=\"$cluster\", instance=\"$primary\"}",
     "legendFormat": "{{ instance }} ⭐️"
    },
    {
     "expr": "pg:instance:load1{cluster=\"$cluster\", instance!=\"$primary\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "CPU Usage 1m",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:cluster:cpu_usage_1m{cluster=\"$cluster\"}",
     "legendFormat": "cluster"
    },
    {
     "expr": "pg:instance:cpu_usage_1m{cluster=\"$cluster\", instance=\"$primary\"}",
     "legendFormat": "{{ instance }} ⭐️"
    },
    {
     "expr": "pg:instance:cpu_usage_1m{cluster=\"$cluster\", instance!=\"$primary\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Read/Write Bandwidth",
   "type": "timeseries",
   "description": "▲ for read bandwidth, ▼ for write bandwidth",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "pg_up{cluster=\"$cluster\"} * 0 + on(ip) node:instance:disk_read_bytes_rate1m",
     "legendFormat": "▲{{ instance }}"
    },
    {
     "expr": "pg_up{cluster=\"$cluster\"} * 0 - on(ip) node:instance:disk_write_bytes_rate1m",
     "legendFormat": "▼{{ instance }}"
    }
   ]
  },
  {
   "title": "Transmit/Receive Bandwidth (Interface)",
   "type": "timeseries",
   "description": "▲ for transmit (out) and ▼ for receive (in)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "node:instance:network_tx_bytes_rate1m{ip=~\"$members\"}",
     "legendFormat": "▲{{ instance }}"
    },
    {
     "expr": "- node:instance:network_rx_bytes_rate1m{ip=~\"$members\"}",
     "legendFormat": "▼{{ instance }}"
    }
   ]
  },
  { "title": "Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Postgres Conn Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:db:conn_usage{cluster=\"$cluster\", datname!~'template\\\\d'}",
     "legendFormat": "{{ instance }}.{{ datname }}"
    }
   ]
  },
  {
   "title": "Pgbouncer Conn Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pgbouncer:db:conn_usage{cluster=\"$cluster\", datname!~'pgbouncer|template\\\\d'}",
     "legendFormat": "{{ instance }}.{{ datname }}"
    }
   ]
  },
  {
   "title": "Postgres Backends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum by (instance) (pg_activity_count{cluster=\"$cluster\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Postgres Backends (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "sum by (instance) (pg_activity_count{cluster=\"$cluster\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Pgbouncer Clients",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "pgbouncer:instance:active_clients{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Pgbouncer Waiting Clients",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "pgbouncer:instance:waiting_clients{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Traefik Open Connections by Entrypoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum by (entrypoint) (traefik_open_connections{entrypoint!~\"traefik|metrics\"})",
     "legendFormat": "{{ entrypoint }}"
    }
   ]
  },
  {
   "title": "Traefik Instance ➔ Entrypoint Connections",
   "type": "timeseries",
   "description": "Session by postgres instance",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance,entrypoint) (traefik_open_connections{entrypoint!~\"traefik|metrics\"})",
     "legendFormat": "{{ instance }} ➔ {{ entrypoint }}"
    }
   ]
  },
  {
   "title": "Traefik Open Connections by Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum by (instance) (traefik_open_connections{entrypoint!~\"traefik|metrics\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Xacts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Cluster Xact Commit Rate",
   "type": "timeseries",
   "description": "Postgres transactions per second according to last 1m, 5m, 15m",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:cluster:xact_commit_rate1m{cluster=\"$cluster\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pg:cluster:xact_commit_rate5m{cluster=\"$cluster\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pg:cluster:xact_commit_rate15m{cluster=\"$cluster\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Cluster Xact Rollback",
   "type": "timeseries",
   "description": "Postgres rollbacked transactions per second according to last 1m, 5m, 15m",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:cluster:xact_rollback_rate1m{cluster=\"$cluster\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pg:cluster:xact_rollback_rate5m{cluster=\"$cluster\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pg:cluster:xact_rollback_rate15m{cluster=\"$cluster\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Transaction RT (avg1m)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg:cluster:active_time_rate1m{cluster=\"$cluster\"} / pg:cluster:xact_total_rate1m{cluster=\"$cluster\"}",
     "legendFormat": "Cluster"
    }
   ]
  },
  {
   "title": "Transaction RT (avg1m)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg:instance:active_time_rate1m{cluster=\"$cluster\"} / pg:instance:xact_total_rate15m{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Transaction Commit by Instances",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (pg:instance:xact_commit_rate1m{cluster=\"$cluster\", instance=\"$primary\"})",
     "legendFormat": "{{ instance }} ⭐️"
    },
    {
     "expr": "sum by (instance) (pg:instance:xact_commit_rate1m{cluster=\"$cluster\", instance!=\"$primary\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Transaction Commit by Database",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (datname) (pg:db:xact_commit_rate1m{cluster=\"$cluster\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Transaction Commit by Instances (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (pg:db:xact_commit_rate1m{cluster=\"$cluster\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Transaction Commit by Database (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (datname) (pg:db:xact_commit_rate1m{cluster=\"$cluster\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Cluster TPS (Pgbouncer)",
   "type": "timeseries",
   "description": "Pgbouncer transactions per second according to last 1m, 5m, 15m",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer:cluster:xact_rate1m{cluster=\"$cluster\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pgbouncer:cluster:xact_rate5m{cluster=\"$cluster\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pgbouncer:cluster:xact_rate15m{cluster=\"$cluster\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Cluster Xact RT (Pgbouncer)",
   "type": "timeseries",
   "description": "Pgbouncer average transaction response time in last 1m, 5m, 15m",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pgbouncer:cluster:xact_rt_1m{cluster=\"$cluster\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pgbouncer:cluster:xact_rt_5m{cluster=\"$cluster\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pgbouncer:cluster:xact_rt_15m{cluster=\"$cluster\"}",
     "legendFormat": "15m"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 109 } },
  {
   "title": "Cluster QPS",
   "type": "timeseries",
   "description": "Pgbouncer Queries per second according to last 1m, 5m, 15m",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer:cluster:query_rate1m{cluster=\"$cluster\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pgbouncer:cluster:query_rate5m{cluster=\"$cluster\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pgbouncer:cluster:query_rate15m{cluster=\"$cluster\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Cluster Query RT",
   "type": "timeseries",
   "description": "Pgbouncer query average response time in last 1m, 5m, 15m",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pgbouncer:cluster:query_rt_1m{cluster=\"$cluster\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pgbouncer:cluster:query_rt_5m{cluster=\"$cluster\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pgbouncer:cluster:query_rt_15m{cluster=\"$cluster\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Leader ${primary} QPS",
   "type": "timeseries",
   "description": "Pgbouncer Queries per second according to last 1m, 5m, 15m",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer:instance:query_rate1m{instance=\"$primary\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pgbouncer:instance:query_rate5m{instance=\"$primary\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pgbouncer:instance:query_rate15m{instance=\"$primary\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Leader ${primary} Query RT",
   "type": "timeseries",
   "description": "Pgbouncer query average response time in last 1m, 5m, 15m",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pgbouncer:instance:query_rt_1m{instance=\"$primary\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pgbouncer:instance:query_rt_5m{instance=\"$primary\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pgbouncer:instance:query_rt_15m{instance=\"$primary\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "QPS by Instance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer:cluster:query_rate5m{cluster=\"$cluster\"}",
     "legendFormat": "Cluster"
    },
    {
     "expr": "pgbouncer:instance:query_rate5m{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Query RT by Instance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pgbouncer:cluster:query_rt_1m{cluster=\"$cluster\"}",
     "legendFormat": "Cluster"
    },
    {
     "expr": "pgbouncer:instance:query_rt_1m{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}