{
 "title": "PGSQL Database",
 "description": "PostgreSQL Database Overview",
 "tags": [
  "FX",
  "PGSQL",
  "Database"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_VMETRICS", "label": "DS (Metrics)", "query": "prometheus" },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(pg_up, instance)" } },
   {
    "name": "datname",
    "label": "Database",
    "query": {
     "query": "label_values(pg_db_age{instance=\"$instance\"},datname)"
    }
   },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(pg_up{instance=\"$instance\"} , instance)"
    }
   },
   {
    "name": "seq",
    "label": "Sequence",
    "query": {
     "query": "label_values(pg_up{instance=\"$instance\"},  instance)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(pg_up{instance=\"$instance\"}, cluster)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{instance=\"$instance\"}, nodename)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Database",
        "type": "string",
        "values": [ "${datname}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Instance",
        "type": "string",
        "values": [ "$instance" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Cluster",
        "type": "string",
        "values": [ "${cluster}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    }
   ]
  },
  {
   "type": "table",
   "description": "All instances among pgsql cluster ${cluster}\n\nInstance: Goto PGSQL Instance\n\nIP: Goto PGSQL Node\n\nStatus: Goto PGSQL Service\n\nLoad: max(cpu,postgres,pgbouncer)\n\nSpace: Disk space usage max(all device)\n\nProxy: session number, Goto Haproxy Admin Page",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "min by (instance,ip) (up{job=\"pgsql\", cluster=\"$cluster\"})"
    },
    {
     "expr": "max by (instance) (pg:instance:load1{cluster=\"$cluster\"})"
    },
    {
     "expr": "sum by (instance) (pg:instance:xact_total_rate1m{cluster=\"$cluster\"})"
    },
    {
     "expr": "min by (instance,ip) (pg_in_recovery{cluster=\"$cluster\"})"
    },
    {
     "expr": "max by (instance) (pg:instance:num_backends{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "type": "table",
   "description": "Database of this cluster ${cluster}",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "sum by (datname) (pg_size_bytes{instance=\"$instance\", datname!~\"wal|log\"})",
     "legendFormat": "Age"
    },
    {
     "expr": "max by (datname) (pg_db_datid{instance=\"$instance\"})",
     "legendFormat": "Conn Limit"
    },
    {
     "expr": "max by (datname) (pg:db:age{instance=\"$instance\"})",
     "legendFormat": "Commit"
    },
    {
     "expr": "max by (datname) (1 - pg_db_is_template{instance=\"$instance\"} + pg_db_allow_conn{instance=\"$instance\"} * 2)",
     "legendFormat": "Status"
    },
    {
     "expr": "sum by (datname) (pg_activity_count{instance=\"$instance\"})",
     "legendFormat": "Session"
    },
    {
     "expr": "sum by (datname) (pg:db:xact_commit_rate1m{instance=\"$instance\"})",
     "legendFormat": "TPS"
    },
    {
     "expr": "max by (datname) (pg_db_conn_limit{instance=\"$instance\"})",
     "legendFormat": "Conn Limit"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:db:xact_commit_rate1m{instance=\"$instance\", datname=\"$datname\"}",
     "legendFormat": "Commit"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:db:xact_rollback_rate1m{instance=\"$instance\", datname=\"$datname\"}",
     "legendFormat": "Rollback"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg:db:ixact_backends{instance=\"$instance\", datname=\"$datname\"})",
     "legendFormat": "iXact"
    }
   ]
  },
  {
   "title": "Table Scan",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "targets": [
    {
     "expr": "pg:table:scan_rate1m{instance=\"$instance\", datname=\"$datname\"}",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Query QPS",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "targets": [
    {
     "expr": "pg:query:call_rate1m{instance=\"$instance\", datname=\"$datname\"}",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_size_bytes{instance=\"$instance\", datname=\"$datname\"})",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pg_db_temp_bytes{instance=\"$instance\", datname=\"$datname\"}[5m]))",
     "legendFormat": "Temp"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_db_numbackends{instance=\"$instance\",datname=\"$datname\"}",
     "legendFormat": "Backend"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 12 },
   "targets": [
    {
     "expr": "sum by (relname) (pg:table:scan_rate1m{instance=\"$instance\", datname=\"$datname\"})"
    },
    {
     "expr": "sum by (relname) (pg_table_n_live_tup{instance=\"$instance\", datname=\"$datname\"})"
    },
    {
     "expr": "sum by (relname) (pg_table_idx_scan{instance=\"$instance\", datname=\"$datname\"}) \n+ sum by (relname) (pg_table_seq_scan{instance=\"$instance\", datname=\"$datname\"})"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (datname, query) (pg_query_calls{instance=\"$instance\", datname=\"$datname\"}) > 0",
     "legendFormat": "{{ query }}"
    },
    {
     "expr": "max by (query) (pg_query_exec_time{instance=\"$instance\", datname=\"$datname\"})",
     "legendFormat": "{{ query }}"
    },
    {
     "expr": "max by (query) (pg:query:rt_1m{instance=\"$instance\", datname=\"$datname\"})",
     "legendFormat": "{{ query }}"
    },
    {
     "expr": "max by (query) (pg:query:call_rate1m{instance=\"$instance\", datname=\"$datname\"})",
     "legendFormat": "{{ query }}"
    },
    {
     "expr": "max by (query) (pg_query_wal_bytes{instance=\"$instance\", datname=\"$datname\"})",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_db_age{instance=\"$instance\", datname=\"$datname\"} / 2147483647",
     "legendFormat": "Age"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:db:conn_usage{instance=\"$instance\", datname=\"$datname\"}",
     "legendFormat": "PG Conn"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg:db:blks_hit_ratio1m{instance=\"$instance\", datname=\"$datname\"}",
     "legendFormat": "Hit Ratio"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:db:tup_fetched_rate1m{instance=\"$instance\", datname=\"$datname\"}",
     "legendFormat": "Row Fetch / s"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:db:tup_modified_rate1m{instance=\"$instance\", datname=\"$datname\"}",
     "legendFormat": "Row Modify / s"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:db:active_time_rate1m{instance=\"$instance\", datname=\"$datname\"}\n/ pg:db:num_backends{instance=\"$instance\", datname=\"$datname\"}",
     "legendFormat": "Active Time"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:db:rlock_count{instance=\"$instance\",datname=\"$datname\"}",
     "legendFormat": "Read Locks"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:db:wlock_count{instance=\"$instance\",datname=\"$datname\"}",
     "legendFormat": "Write Locks"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:db:xlock_count{instance=\"$instance\",datname=\"$datname\"}",
     "legendFormat": "EX Locks"
    }
   ]
  },
  {
   "title": "Session",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_db_numbackends{instance=\"$instance\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:instance:xact_commit_rate1m{instance=\"$instance\"}",
     "legendFormat": "Instance"
    },
    {
     "expr": "pg:db:xact_commit_rate1m{instance=\"$instance\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  { "title": "Pgbouncer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pgbouncer:db:active_servers{instance=\"$instance\",datname=\"$datname\"})",
     "legendFormat": "Pool Server"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pgbouncer:db:active_clients{instance=\"$instance\",datname=\"$datname\"})",
     "legendFormat": "Pool Client"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer:db:conn_usage{instance=\"$instance\", datname=\"$datname\"}",
     "legendFormat": "PGB Conn"
    }
   ]
  },
  {
   "title": "Databases in Pgbouncer",
   "type": "table",
   "description": "Database in Pgbouncer of this instance ${instance}",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 29 },
   "targets": [
    {
     "expr": "sum by (datname,host,real_datname) (pgbouncer_database_pool_size{instance=\"$instance\", datname!=\"pgbouncer\"})",
     "legendFormat": "Pool Size"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_reserve_pool{instance=\"$instance\", datname!=\"pgbouncer\"})",
     "legendFormat": "Pool Resv"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_current_connections{instance=\"$instance\", datname!=\"pgbouncer\"})",
     "legendFormat": "Conn"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_max_connections{instance=\"$instance\", datname!=\"pgbouncer\"})",
     "legendFormat": "Conn Max"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_current_connections{instance=\"$instance\", datname!=\"pgbouncer\"}) / sum by (datname) (pgbouncer_database_max_connections{instance=\"$instance\", datname!=\"pgbouncer\"})",
     "legendFormat": "Conn Usage"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_disabled{instance=\"$instance\", datname!=\"pgbouncer\"})",
     "legendFormat": "Disabled"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_paused{instance=\"$instance\", datname!=\"pgbouncer\"})",
     "legendFormat": "Paused"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer:db:xact_rate1m{instance=\"$instance\",datname=\"$datname\"}",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer:db:xact_rt_1m{instance=\"$instance\", datname=\"$datname\"}",
     "legendFormat": "Xact RT"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) (pgbouncer_pool_waiting_clients{instance=\"$instance\", datname=\"$datname\"})",
     "legendFormat": "Queue"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer:db:query_rate1m{instance=\"$instance\",datname=\"$datname\"}",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer:db:query_rt_1m{instance=\"$instance\", datname=\"$datname\"}",
     "legendFormat": "Query RT"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pgbouncer:db:rx_rate1m{instance=\"$instance\", datname=\"$datname\"}) + sum(pgbouncer:db:tx_rate1m{instance=\"$instance\", datname=\"$datname\"})",
     "legendFormat": "Traffic"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Row Returned / Fetched",
   "type": "timeseries",
   "description": "Tuples fetched/returned from databases",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(pg_db_tup_fetched{instance=\"$instance\", datname=\"$datname\"}[5m])",
     "legendFormat": "Fetched"
    },
    {
     "expr": "rate(pg_db_tup_returned{instance=\"$instance\", datname=\"$datname\"}[5m])",
     "legendFormat": "Returned"
    }
   ]
  },
  {
   "title": "Row Modified",
   "type": "timeseries",
   "description": "Tuples fetched, inserted, updated, delete among this cluster",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(pg_db_tup_inserted{instance=\"$instance\", datname=\"$datname\"}[1m])",
     "legendFormat": "INSERTED"
    },
    {
     "expr": "rate(pg_db_tup_updated{instance=\"$instance\", datname=\"$datname\"}[1m])",
     "legendFormat": "UPDATED"
    },
    {
     "expr": "rate(pg_db_tup_deleted{instance=\"$instance\", datname=\"$datname\"}[1m])",
     "legendFormat": "DELETED"
    }
   ]
  },
  {
   "title": "Xact Commit / Rollback",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_db_xact_commit{instance=\"$instance\", datname=\"$datname\"}[3m])",
     "legendFormat": "commit"
    },
    {
     "expr": "rate(pg_db_xact_rollback{instance=\"$instance\", datname=\"$datname\"}[3m])",
     "legendFormat": "rollback"
    }
   ]
  },
  {
   "title": "Long Lived Xact",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (datname) (pg_activity_max_tx_duration{instance=\"$instance\", datname=\"$datname\", state=\"active\"})",
     "legendFormat": "Long Lived Xact"
    }
   ]
  },
  {
   "title": "Locks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (mode) (pg_lock_count{instance=\"$instance\", datname=\"$datname\"})",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Blocks Hit Ratio (1m)",
   "type": "timeseries",
   "description": "Database 4k blocks hit ratio in last 1 minute of database ${datname}\n\n`pg_stat_database`:\n\n`blks_hit` / (`blks_read` + `blks_hit`) in last minute",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:db:blks_hit_ratio1m{instance=\"$instance\", datname='$datname'}",
     "legendFormat": "Hit Ratio"
    },
    { "expr": "1", "legendFormat": "100%" }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Query QPS (5m)",
   "type": "timeseries",
   "description": "Query QPS of this database ${datname} on ${instance} in last 5 minutes.\n\nrate 5m of `pg_stat_statements`.`calls`\nClick datapoint to check a specific query.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(pgbouncer_stat_total_query_count{instance=\"$instance\", datname=\"$datname\"}[5m])",
     "legendFormat": "Pgbouncer QPS"
    },
    {
     "expr": "rate(pg_db_xact_commit{instance=\"$instance\", datname=\"$datname\"}[5m])",
     "legendFormat": "Postgres TPS"
    },
    {
     "expr": "rate(pg_query_calls{instance=\"$instance\", datname=\"$datname\"}[5m])",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Query RT (1m)",
   "type": "timeseries",
   "description": "Query RT of this database ${datname} on ${instance}.\n\nrate 5m of `total_exec_time` / `calls`\n\nClick datapoint to check a specific query.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pgbouncer_stat_total_query_time{instance=\"$instance\", datname=\"$datname\"}[5m]) /\nrate(pgbouncer_stat_total_query_count{instance=\"$instance\", datname=\"$datname\"}[5m])",
     "legendFormat": "Pgbouncer RT"
    },
    {
     "expr": "rate(pg_db_active_time{instance=\"$instance\", datname=\"$datname\"}[5m]) /\nrate(pg_db_xact_commit{instance=\"$instance\", datname=\"$datname\"}[5m])",
     "legendFormat": "Postgres RT"
    },
    {
     "expr": "pg:query:rt_1m{instance=\"$instance\",datname=\"$datname\"}",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Exec Time / RT Matrix (1h)",
   "type": "marcusolsson-treemap-panel",
   "description": "Size by exec time spent in last hour, Colored by RT in last hour",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "increase(pg_query_exec_time{instance=\"$instance\", datname=\"$datname\"}[1h])",
     "legendFormat": "__auto",
     "rawSql": "SELECT queryid::TEXT AS qid, d.datname, r.rolname, s.rows AS value, s.mean_exec_time AS rt\nFROM pg_stat_statements s\n         LEFT JOIN pg_database d ON s.dbid = d.oid\n         LEFT JOIN pg_roles r ON s.userid = r.oid\nWHERE datname='$datname' AND rows > 0\nORDER BY calls DESC\nLIMIT 100;"
    },
    {
     "expr": "increase(pg_query_exec_time{instance=\"$instance\", datname=\"$datname\"}[1h]) /\n increase(pg_query_calls{instance=\"$instance\", datname=\"$datname\"}[1h])",
     "legendFormat": "__auto",
     "rawSql": "SELECT queryid::TEXT AS qid, d.datname, r.rolname, s.rows AS value, s.mean_exec_time AS rt\nFROM pg_stat_statements s\n         LEFT JOIN pg_database d ON s.dbid = d.oid\n         LEFT JOIN pg_roles r ON s.userid = r.oid\nWHERE datname='$datname' AND rows > 0\nORDER BY calls DESC\nLIMIT 100;"
    }
   ]
  },
  {
   "title": "Rows Returned (5m)",
   "type": "timeseries",
   "description": "Numbers of rows returned of each query in this database ${datname} on ${instance} in last 5 minutes.\n\nrate 5m of `pg_stat_statements`.`calls`\nClick datapoint to check a specific query.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "rowsps" } },
   "targets": [
    {
     "expr": "rate(pg_db_tup_returned{instance=\"$instance\", datname=\"$datname\"}[5m])",
     "legendFormat": "Postgres RPS"
    },
    {
     "expr": "rate(pg_query_rows{instance=\"$instance\", datname=\"$datname\"}[5m])",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Exec Time Spent (1h)",
   "type": "piechart",
   "description": "Time spent on executing statements during last 1 hour.\n\nincrease1h of `pg_stat_statements`.`total_exec_time`",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(pg_query_exec_time{instance=\"$instance\", datname=\"$datname\"}[1h])",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Exec Time Spent (5m)",
   "type": "timeseries",
   "description": "Exec Time Spent of this database ${datname} on ${instance}.\n\nrate 5m of `pg_stat_statements`.`calls`\nClick datapoint to check a specific query.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pgbouncer_stat_total_query_time{instance=\"$instance\", datname=\"$datname\"}[5m])",
     "legendFormat": "Pgbouncer Time"
    },
    {
     "expr": "rate(pg_db_active_time{instance=\"$instance\", datname=\"$datname\"}[5m])",
     "legendFormat": "Postgres Time"
    },
    {
     "expr": "rate(pg_query_exec_time{instance=\"$instance\", datname=\"$datname\"}[5m])",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "Blocks Access (1h)",
   "type": "piechart",
   "description": "Shared blocks access & read size in bytes, in last 1 hour of each query.\n\n`pg_stat_statements`: `share_blks_read` + `shared_blks_hit`",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(pg_query_sblk_read{instance=\"$instance\", datname=\"$datname\"}[1h]) +\nincrease(pg_query_sblk_hit{instance=\"$instance\", datname=\"$datname\"}[1h])) * 8192",
     "legendFormat": "{{ query }}"
    }
   ]
  },
  {
   "title": "WAL Bytes (5m)",
   "type": "timeseries",
   "description": "Numbers of wal bytes generated of each query in this database ${datname} on ${instance} in last 5 minutes.\n\nrate 5m of `pg_stat_statements`.`wal_bytes`\n\nClick the data-point to check a specific query.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(pg_lsn{instance=\"$instance\"}[5m])",
     "legendFormat": "Postgres LSN"
    },
    {
     "expr": "rate(pg_query_wal_bytes{instance=\"$instance\", datname=\"$datname\"}[5m])",
     "legendFormat": "{{ query }}"
    }
   ]
  }
 ]
}