{
 "title": "PGSQL Table",
 "description": "PostgreSQL Single Table Dashboard",
 "tags": [
  "FX",
  "PGSQL",
  "Database",
  "Table"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_VMETRICS", "label": "DS (Metrics)", "query": "prometheus" },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(pg_up, instance)" } },
   {
    "name": "datname",
    "label": "Database",
    "query": {
     "query": "label_values(pg_db_age{instance=\"$instance\"}, datname)"
    }
   },
   {
    "name": "relname",
    "label": "Table",
    "query": {
     "query": "label_values(pg_table_idx_scan{instance=\"$instance\", datname=\"$datname\"},relname)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{instance=\"$instance\"}, nodename)"
    }
   },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(pg_up{instance=\"$instance\"} , instance)"
    }
   },
   {
    "name": "seq",
    "label": "Sequence",
    "query": {
     "query": "label_values(pg_up{instance=\"$instance\"},  instance)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(pg_up{instance=\"$instance\"}, cluster)"
    }
   },
   {
    "name": "nspname",
    "label": "Schema",
    "query": {
     "query": "label_values(pg_table_idx_scan{relname=\"$relname\"},relname)"
    }
   },
   {
    "name": "tblname",
    "label": "TableName",
    "query": {
     "query": "label_values(pg_table_idx_scan{relname=\"$relname\"},relname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Relation",
        "type": "string",
        "values": [ "${relname}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Database",
        "type": "string",
        "values": [ "${datname}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Instance",
        "type": "string",
        "values": [ "$instance" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Cluster",
        "type": "string",
        "values": [ "${cluster}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    }
   ]
  },
  {
   "type": "table",
   "description": "All instances among pgsql cluster ${cluster}\n\nInstance: Goto PGSQL Instance\n\nIP: Goto PGSQL Node\n\nStatus: Goto PGSQL Service\n\nLoad: max(cpu,postgres,pgbouncer)\n\nSpace: Disk space usage max(all device)\n\nProxy: session number, Goto Haproxy Admin Page",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "min by (instance,ip) (up{job=\"pgsql\", cluster=\"$cluster\"})"
    },
    {
     "expr": "max by (instance) (pg:instance:load1{cluster=\"$cluster\"})"
    },
    {
     "expr": "sum by (instance) (pg:instance:xact_total_rate1m{cluster=\"$cluster\"})"
    },
    {
     "expr": "min by (instance,ip) (pg_in_recovery{cluster=\"$cluster\"})"
    },
    {
     "expr": "max by (instance) (pg:instance:num_backends{cluster=\"$cluster\"})"
    },
    {
     "expr": "max by (instance) (pgbouncer:instance:xact_rt_1m{cluster=\"$cluster\"})"
    },
    { "expr": "vector(0)" }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "sum by (relname) (pg:table:scan_rate1m{instance=\"$instance\", datname=\"$datname\"})"
    },
    {
     "expr": "sum by (relname) (pg_table_n_live_tup{instance=\"$instance\", datname=\"$datname\"})"
    },
    {
     "expr": "sum by (relname) (pg_table_size_bytes{instance=\"$instance\", datname=\"$datname\"})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_table_relid{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}",
     "legendFormat": "OID"
    },
    {
     "expr": "pg_table_ncols{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}",
     "legendFormat": "Columns"
    },
    {
     "expr": "pg_table_tuples{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}",
     "legendFormat": "Rows"
    },
    {
     "expr": "pg_table_size_bytes{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}",
     "legendFormat": "Size"
    },
    {
     "expr": "pg_table_age{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}",
     "legendFormat": "Age"
    },
    {
     "expr": "rate(pg_table_tup_read{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "Row Read"
    },
    {
     "expr": "rate(pg_table_n_tup_mod{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "Row Mod"
    },
    {
     "expr": "pg_table_n_tup_mod{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}\n/( 1 + pg_table_tup_read{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"})",
     "legendFormat": "Row W/R %"
    },
    {
     "expr": "(pg_table_seq_scan{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"} + pg_table_idx_scan{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"})",
     "legendFormat": "Scan"
    },
    {
     "expr": "rate(pg_table_seq_scan{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[5m])",
     "legendFormat": "Seq Scan"
    },
    {
     "expr": "rate(pg_table_idx_scan{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[5m])",
     "legendFormat": "Idx Scan"
    }
   ]
  },
  {
   "title": "Table Scan",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "qps" } },
   "targets": [
    {
     "expr": "pg:table:scan_rate1m{instance=\"$instance\", datname=\"$datname\"}",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  { "title": "Scan & Access", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Table Scan Rate",
   "type": "timeseries",
   "description": "Total scan (index + seq) rate of last 1 minute on this table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_idx_scan{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "Index"
    },
    {
     "expr": "rate(pg_table_seq_scan{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "Sequential"
    }
   ]
  },
  {
   "title": "Row Scan Rate",
   "type": "timeseries",
   "description": "Total scan (index + seq) rate of last 1 minute on this table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_idx_tup_fetch{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "Index"
    },
    {
     "expr": "rate(pg_table_seq_tup_read{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "Sequential"
    }
   ]
  },
  {
   "title": "Index Scan Rate",
   "type": "timeseries",
   "description": "Index scan rate of last 1 minute on this table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_idx_scan{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "rate1m"
    },
    {
     "expr": "rate(pg_table_idx_scan{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[5m])",
     "legendFormat": "rate5m"
    }
   ]
  },
  {
   "title": "Sequential Scan Rate",
   "type": "timeseries",
   "description": "Sequential scan rate of last 1 minute on this table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_seq_scan{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "rate1m"
    },
    {
     "expr": "rate(pg_table_seq_scan{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[5m])",
     "legendFormat": "rate5m"
    }
   ]
  },
  { "title": "Modification", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Rows Modified (5m)",
   "type": "timeseries",
   "description": "Tuple Modification (insert|delete|update) in last 5 minutes",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(pg_table_n_tup_ins{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[5m])",
     "legendFormat": "INSERT"
    },
    {
     "expr": "increase(pg_table_n_tup_del{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[5m])",
     "legendFormat": "DELETE"
    },
    {
     "expr": "increase(pg_table_n_tup_upd{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[5m])",
     "legendFormat": "UPDATE"
    }
   ]
  },
  {
   "title": "Inserts",
   "type": "timeseries",
   "description": "Tuple insert rate of last 1 minute & 5 minute",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_n_tup_ins{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "rate1m"
    },
    {
     "expr": "rate(pg_table_n_tup_ins{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[5m])",
     "legendFormat": "rate5m"
    }
   ]
  },
  {
   "title": "Updates",
   "type": "timeseries",
   "description": "Tuple insert rate of last 1 minute & 5 minute",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_n_tup_upd{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "rate1m"
    },
    {
     "expr": "rate(pg_table_n_tup_upd{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[5m])",
     "legendFormat": "rate5m"
    }
   ]
  },
  {
   "title": "Deletes",
   "type": "timeseries",
   "description": "Tuple insert rate of last 1 minute & 5 minute",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_n_tup_del{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "rate1m"
    },
    {
     "expr": "rate(pg_table_n_tup_del{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[5m])",
     "legendFormat": "rate5m"
    }
   ]
  },
  {
   "title": "HOT Updates",
   "type": "timeseries",
   "description": "Rate1m of rows HOT updated",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(pg_table_n_tup_hot_upd{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "rate1m"
    },
    {
     "expr": "rate(pg_table_n_tup_hot_upd{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[5m])",
     "legendFormat": "rate5m"
    }
   ]
  },
  {
   "title": "HOT Rate",
   "type": "timeseries",
   "description": "Rate1m of rows HOT updated",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(pg_table_n_tup_hot_upd{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m]) / increase(pg_table_n_tup_upd{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "HOT Rate"
    }
   ]
  },
  { "title": "Indexes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Index Scan Rate",
   "type": "timeseries",
   "description": "Index scan rate of last 1 minute on this table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_index_idx_scan{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "{{ idxname }}"
    }
   ]
  },
  {
   "title": "Index Block Hit Rate",
   "type": "timeseries",
   "description": "Rate1m of rows HOT updated",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(pg_index_idx_blks_hit{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m]) / (rate(pg_index_idx_blks_read{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m]) + rate(pg_index_idx_blks_hit{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m]))",
     "legendFormat": "{{ idxname }}"
    }
   ]
  },
  {
   "title": "Index Tuple Returned",
   "type": "timeseries",
   "description": "Rate of index tuples been read",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_index_idx_tup_read{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "{{ idxname }}"
    }
   ]
  },
  {
   "title": "Index Tuple Fetched",
   "type": "timeseries",
   "description": "Rate of live table rows fetched by simple index scans using this index",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_index_idx_tup_fetch{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "{{ idxname }}"
    }
   ]
  },
  {
   "title": "Tuple Returned Per Scan",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(pg_index_idx_tup_read{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m]) / increase(pg_index_idx_scan{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "{{ idxname }}"
    }
   ]
  },
  {
   "title": "Tuple Fetched Per Scan",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(pg_index_idx_tup_fetch{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m]) / increase(pg_index_idx_scan{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m])",
     "legendFormat": "{{ idxname }}"
    }
   ]
  },
  { "title": "Sequences", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Sequence Values",
   "type": "stat",
   "description": "Total scan (index + seq) rate of last 1 minute on this table",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_seq_last_value{instance=\"$instance\", datname=\"$datname\", seqname=~\"$relname.*\"}",
     "legendFormat": "{{ seqname }}"
    }
   ]
  },
  {
   "title": "Sequence Allocation (1m)",
   "type": "timeseries",
   "description": "Index scan tuples/s of last 1 minute",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(pg_seq_last_value{instance=\"$instance\", datname=\"$datname\", seqname=~\"$relname.*\"}[1m])",
     "legendFormat": "{{ seqname }}"
    }
   ]
  },
  {
   "title": "Functions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 },
   "panels": [
    {
     "title": "Function Call",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(pg_func_calls{instance=\"$instance\", datname=\"$datname\", funcname=~\".*$relname.*\"}[1m])",
       "legendFormat": "{{ funcname }}"
      }
     ]
    },
    {
     "title": "Function Time Spend (Stacked)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(pg_func_total_time{instance=\"$instance\", datname=\"$datname\", funcname=~\".*$relname.*\"}[1m]) / rate(pg_func_calls{instance=\"$instance\", datname=\"$datname\", funcname=~\".*$relname.*\"}[1m])",
       "legendFormat": "{{ funcname }}"
      }
     ]
    },
    {
     "title": "Function Duration (Self Time)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(pg_func_self_time{instance=\"$instance\", datname=\"$datname\", funcname=~\".*$relname.*\"}[1m]) / rate(pg_func_calls{instance=\"$instance\", datname=\"$datname\", funcname=~\".*$relname.*\"}[1m])",
       "legendFormat": "{{ funcname }}"
      }
     ]
    },
    {
     "title": "Function Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(pg_func_total_time{instance=\"$instance\", datname=\"$datname\", funcname=~\".*$relname.*\"}[1m]) / rate(pg_func_calls{instance=\"$instance\", datname=\"$datname\", funcname=~\".*$relname.*\"}[1m])",
       "legendFormat": "{{ funcname }}"
      }
     ]
    }
   ]
  },
  { "title": "Blocks I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Table Heap Block Hit Rate",
   "type": "timeseries",
   "description": "Rate1m of rows HOT updated",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(pg_table_heap_blks_hit{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m]) / (rate(pg_table_heap_blks_read{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m]) + rate(pg_table_heap_blks_hit{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m]))",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Table Index Block Hit Rate",
   "type": "timeseries",
   "description": "Rate1m of rows HOT updated",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(pg_table_idx_blks_hit{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m]) / (rate(pg_table_idx_blks_read{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m]) + rate(pg_table_idx_blks_hit{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m]))",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Table Toast Block Hit Rate",
   "type": "timeseries",
   "description": "Rate1m of rows HOT updated",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(pg_table_toast_blks_hit{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m]) / (rate(pg_table_toast_blks_read{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m]) + rate(pg_table_toast_blks_hit{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m]))",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Table Toast Index Block Hit Rate",
   "type": "timeseries",
   "description": "Rate1m of rows HOT updated",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(pg_table_tidx_blks_hit{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m]) / (rate(pg_table_tidx_blks_read{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m]) + rate(pg_table_tidx_blks_hit{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m]))",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Vacuum & Analyze",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 },
   "panels": [
    {
     "title": "Maintenance Activity",
     "type": "state-timeline",
     "description": "Vacuum and analyze activity on this table (manual or auto)",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 102 },
     "targets": [
      {
       "expr": "increase(pg_table_vacuum_count{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m])",
       "legendFormat": "Vacuum"
      },
      {
       "expr": "increase(pg_table_autovacuum_count{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m])",
       "legendFormat": "Auto Vacuum"
      },
      {
       "expr": "increase(pg_table_analyze_count{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m])",
       "legendFormat": "Analyze"
      },
      {
       "expr": "increase(pg_table_autoanalyze_count{instance=\"$instance\", datname=\"$datname\", relname=\"$relname\"}[1m])",
       "legendFormat": "Auto Analyze"
      }
     ]
    }
   ]
  }
 ]
}