{
 "title": "PGSQL Xacts",
 "description": "PostgreSQL Transaction detail for instance",
 "tags": [
  "FX",
  "PGSQL",
  "Instance"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_VMETRICS", "label": "DS (Metrics)", "query": "prometheus" },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(pg_up, instance)" } },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(pg_up{instance=\"$instance\"} , instance)"
    }
   },
   {
    "name": "seq",
    "label": "Sequence",
    "query": {
     "query": "label_values(pg_up{instance=\"$instance\"},  instance)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(pg_up{instance=\"$instance\"}, cluster)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{instance=\"$instance\"}, nodename)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Instance",
        "type": "string",
        "values": [ "$instance" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Cluster",
        "type": "string",
        "values": [ "${cluster}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Node IP",
        "type": "string",
        "values": [ "${ip}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Hostname",
        "type": "string",
        "values": [ "${node}" ]
       }
      ],
      "meta": {}
     }
    }
   ]
  },
  {
   "title": "Postgres Instances",
   "type": "table",
   "description": "All instances among pgsql cluster ${cluster}\n\nInstance: Goto PGSQL Instance\n\nIP: Goto PGSQL Node\n\nStatus: Goto PGSQL Service\n\nLoad: max(cpu,postgres,pgbouncer)\n\nSpace: Disk space usage max(all device)\n\nProxy: session number, Goto Haproxy Admin Page",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "pg_in_recovery{cluster=\"$cluster\"}"
    },
    {
     "expr": "instance:pressure1{cluster=\"$cluster\"}"
    },
    {
     "expr": "sum by (instance) (pg:instance:xact_total_rate1m{cluster=\"$cluster\"})"
    },
    {
     "expr": "max by (instance) (pg:instance:num_backends{cluster=\"$cluster\"})"
    },
    {
     "expr": "max by (instance) (pgbouncer:instance:xact_rt_1m{cluster=\"$cluster\"})"
    },
    {
     "expr": "max by (instance) (pg:instance:conn_usage{cluster=\"$cluster\"})"
    },
    {
     "expr": "sum by (instance) (pgbouncer:instance:query_rate1m{cluster=\"$cluster\"})"
    },
    {
     "expr": "sum by (instance) (pgbouncer:instance:waiting_clients{cluster=\"$cluster\"})"
    },
    {
     "expr": "max by (instance) (pg:instance:lag_bytes{cluster=\"$cluster\", instance=~'$cluster.*'})"
    },
    {
     "expr": "min by (instance) (up{cluster=\"$cluster\", job=\"pgsql\"})"
    }
   ]
  },
  { "title": "Postgres Xacts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Transaction Commit",
   "type": "timeseries",
   "description": "Pgbouncer transactions per second according to last 1m, 5m, 15m",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:instance:xact_commit_rate1m{instance=\"$instance\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pg:instance:xact_commit_rate5m{instance=\"$instance\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pg:instance:xact_commit_rate15m{instance=\"$instance\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Transaction Rollback",
   "type": "timeseries",
   "description": "postgres rollbacked transactions per second according to last 1m, 5m, 15m",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:instance:xact_rollback_rate1m{instance=\"$instance\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pg:instance:xact_rollback_rate1m{instance=\"$instance\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pg:instance:xact_rollback_rate1m{instance=\"$instance\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "TPS Variation σ/µ (5m)",
   "type": "timeseries",
   "description": "coefficient of variation, CV of TPS in last 5 minutes",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "stddev_over_time(pg:instance:xact_commit_rate1m{instance=\"$instance\"}[5m])/\navg_over_time(pg:instance:xact_commit_rate1m{instance=\"$instance\"}[5m])",
     "legendFormat": "QPS CV"
    }
   ]
  },
  {
   "title": "Rollback Ratio",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:instance:xact_rollback_rate1m{instance=\"$instance\"} / pg:instance:xact_total_rate1m{instance=\"$instance\"}",
     "legendFormat": "Rollback Rate"
    }
   ]
  },
  {
   "title": "Transaction Commit by Database",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:db:xact_commit_rate1m{instance=\"$instance\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Long Lived Xact",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (state) (pg_activity_max_tx_duration{instance=\"$instance\", state!~\"(idle.*|disabled)\"})",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  { "title": "Locks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Locks Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (pg_lock_count{instance=\"$instance\"})",
     "legendFormat": "Locks"
    }
   ]
  },
  {
   "title": "Locks",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (mode) (pg_lock_count{instance=\"$instance\"})",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Locks by Category",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:instance:xlock_count{instance=\"$instance\"}",
     "legendFormat": "Exclusive"
    },
    {
     "expr": "pg:instance:wlock_count{instance=\"$instance\"}",
     "legendFormat": "Write"
    },
    {
     "expr": "pg:instance:rlock_count{instance=\"$instance\"}",
     "legendFormat": "Read"
    }
   ]
  },
  { "title": "Pgbouncer Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "TPS Seasonality",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer:instance:xact_rate5m{instance=\"$instance\"}",
     "legendFormat": "TPS"
    },
    {
     "expr": "pgbouncer:instance:xact_rate5m{instance=\"$instance\"} OFFSET 1d",
     "legendFormat": "Yesterday"
    },
    {
     "expr": "pgbouncer:instance:xact_rate5m{instance=\"$instance\"} OFFSET 2d",
     "legendFormat": "2 Day Ago"
    }
   ]
  },
  {
   "title": "Average Queries per Xact",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer:instance:query_rate1m{instance=\"$instance\"} / pgbouncer:instance:xact_rate1m{instance=\"$instance\"}",
     "legendFormat": "Q"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "description": "Pgbouncer transactions per second according to last 1m, 5m, 15m",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer:instance:xact_rate1m{instance=\"$instance\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pgbouncer:instance:xact_rate5m{instance=\"$instance\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pgbouncer:instance:xact_rate15m{instance=\"$instance\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Xact RT",
   "type": "timeseries",
   "description": "Pgbouncer average transaction response time in last 1m, 5m, 15m",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pgbouncer:instance:xact_rt_1m{instance=\"$instance\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pgbouncer:instance:xact_rt_5m{instance=\"$instance\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pgbouncer:instance:xact_rt_15m{instance=\"$instance\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Pgbouncer TPS Variation σ/µ (5m)",
   "type": "timeseries",
   "description": "coefficient of variation, CV of Pgbouncer TPS in last 5 minutes",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "stddev_over_time(pgbouncer:instance:xact_rate1m{instance=\"$instance\"}[5m])/\navg_over_time(pgbouncer:instance:xact_rate1m{instance=\"$instance\"}[5m])",
     "legendFormat": "QPS CV"
    }
   ]
  },
  {
   "title": "Pgbouncer RT Variation σ/µ (5m)",
   "type": "timeseries",
   "description": "coefficient of variation, CV of Pgbouncer Xact RT in last 5 minutes",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "stddev_over_time(pgbouncer:instance:xact_rt_5m{instance=\"$instance\"}[5m])/\navg_over_time(pgbouncer:instance:xact_rt_5m{instance=\"$instance\"}[5m])",
     "legendFormat": "QPS CV"
    }
   ]
  },
  {
   "title": "TPS Distribution",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(pgbouncer:instance:xact_rate1m{instance=\"$instance\"}[15m]) + 3 * stddev_over_time(pgbouncer:instance:xact_rate1m{instance=\"$instance\"}[15m])",
     "legendFormat": "+3σ"
    },
    {
     "expr": "avg_over_time(pgbouncer:instance:xact_rate1m{instance=\"$instance\"}[15m]) - 3 * stddev_over_time(pgbouncer:instance:xact_rate1m{instance=\"$instance\"}[15m])",
     "legendFormat": "-3σ"
    },
    {
     "expr": "avg_over_time(pgbouncer:instance:xact_rate1m{instance=\"$instance\"}[15m]) + stddev_over_time(pgbouncer:instance:xact_rate1m{instance=\"$instance\"}[15m])",
     "legendFormat": "+σ"
    },
    {
     "expr": "avg_over_time(pgbouncer:instance:xact_rate1m{instance=\"$instance\"}[15m]) - stddev_over_time(pgbouncer:instance:xact_rate1m{instance=\"$instance\"}[15m])",
     "legendFormat": "-σ"
    },
    {
     "expr": "avg_over_time(pgbouncer:instance:xact_rate1m{instance=\"$instance\"}[15m])",
     "legendFormat": "µ"
    },
    {
     "expr": "pgbouncer:instance:xact_rate1m{instance=\"$instance\"}",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "RT Distribution",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(pgbouncer:instance:xact_rt_1m{instance=\"$instance\"}[15m]) + 3 * stddev_over_time(pgbouncer:instance:xact_rt_1m{instance=\"$instance\"}[15m])",
     "legendFormat": "+3σ"
    },
    {
     "expr": "avg_over_time(pgbouncer:instance:xact_rt_1m{instance=\"$instance\"}[15m]) - 3 * stddev_over_time(pgbouncer:instance:xact_rt_1m{instance=\"$instance\"}[15m]) ",
     "legendFormat": "-3σ"
    },
    {
     "expr": "avg_over_time(pgbouncer:instance:xact_rt_1m{instance=\"$instance\"}[15m]) + stddev_over_time(pgbouncer:instance:xact_rt_1m{instance=\"$instance\"}[15m])",
     "legendFormat": "+σ"
    },
    {
     "expr": "avg_over_time(pgbouncer:instance:xact_rt_1m{instance=\"$instance\"}[15m]) - stddev_over_time(pgbouncer:instance:xact_rt_1m{instance=\"$instance\"}[15m])",
     "legendFormat": "-σ"
    },
    {
     "expr": "avg_over_time(pgbouncer:instance:xact_rt_1m{instance=\"$instance\"}[15m])",
     "legendFormat": "µ"
    },
    {
     "expr": "pgbouncer:instance:xact_rt_1m{instance=\"$instance\"}",
     "legendFormat": "v"
    }
   ]
  },
  {
   "title": "TPS by Database",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer:instance:xact_rate5m{instance=\"$instance\"}",
     "legendFormat": "Instance"
    },
    {
     "expr": "pgbouncer:db:xact_rate5m{instance=\"$instance\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "TPS by Instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer:cluster:xact_rate5m{cluster=\"$cluster\"}",
     "legendFormat": "Cluster"
    },
    {
     "expr": "pgbouncer:instance:xact_rate5m{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Xact RT by Database",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pgbouncer:instance:xact_rt_1m{instance=\"$instance\"}",
     "legendFormat": "Instance"
    },
    {
     "expr": "pgbouncer:db:xact_rt_1m{instance=\"$instance\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Xact RT by Instance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pgbouncer:cluster:xact_rt_1m{cluster=\"$cluster\"}",
     "legendFormat": "Cluster"
    },
    {
     "expr": "pgbouncer:instance:xact_rt_1m{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}