{
 "title": "PGSQL Session",
 "description": "PostgreSQL Session of Single Instance",
 "tags": [
  "FX",
  "PGSQL",
  "Instance"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_VMETRICS", "label": "DS (Metrics)", "query": "prometheus" },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(pg_up, instance)" } },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(pg_up{instance=\"$instance\"} , instance)"
    }
   },
   {
    "name": "seq",
    "label": "Sequence",
    "query": {
     "query": "label_values(pg_up{instance=\"$instance\"},  instance)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(pg_up{instance=\"$instance\"}, cluster)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{instance=\"$instance\"}, nodename)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Instance",
        "type": "string",
        "values": [ "$instance" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Cluster",
        "type": "string",
        "values": [ "${cluster}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Node IP",
        "type": "string",
        "values": [ "${ip}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Hostname",
        "type": "string",
        "values": [ "${node}" ]
       }
      ],
      "meta": {}
     }
    }
   ]
  },
  {
   "title": "Postgres Instances",
   "type": "table",
   "description": "All instances among pgsql cluster ${cluster}\n\nInstance: Goto PGSQL Instance\n\nIP: Goto PGSQL Node\n\nStatus: Goto PGSQL Service\n\nLoad: max(cpu,postgres,pgbouncer)\n\nSpace: Disk space usage max(all device)\n\nProxy: session number, Goto Haproxy Admin Page",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "pg_in_recovery{cluster=\"$cluster\"}"
    },
    {
     "expr": "instance:pressure1{cluster=\"$cluster\"}"
    },
    {
     "expr": "sum by (instance) (pg:instance:xact_total_rate1m{cluster=\"$cluster\"})"
    },
    {
     "expr": "max by (instance) (pg:instance:num_backends{cluster=\"$cluster\"})"
    },
    {
     "expr": "max by (instance) (pgbouncer:instance:xact_rt_1m{cluster=\"$cluster\"})"
    },
    {
     "expr": "max by (instance) (pg:instance:conn_usage{cluster=\"$cluster\"})"
    },
    {
     "expr": "sum by (instance) (pgbouncer:instance:query_rate1m{cluster=\"$cluster\"})"
    },
    {
     "expr": "sum by (instance) (pgbouncer:instance:waiting_clients{cluster=\"$cluster\"})"
    },
    {
     "expr": "max by (instance) (pg:instance:lag_bytes{cluster=\"$cluster\", instance=~'$cluster.*'})"
    },
    {
     "expr": "min by (instance) (up{cluster=\"$cluster\", job=\"pgsql\"})"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Connection Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:instance:conn_usage{instance=\"$instance\"}",
     "legendFormat": "Postgres"
    }
   ]
  },
  {
   "title": "Idle in Transaction Backends",
   "type": "timeseries",
   "description": "Idle in Transaction backend number of all databases in this instance.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (datname) (pg_activity_count{instance=\"$instance\", state=~\"idle in.*\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Backends by State",
   "type": "timeseries",
   "description": "Group by pg_stat_activity.state on instance level",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (state) (pg_activity_count{instance=\"$instance\"})",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Backends by Type",
   "type": "timeseries",
   "description": "Backend number group by backend type in this instance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum by (type) (pg_backend_count{instance=\"$instance\"})",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Max Conn Lifespan",
   "type": "timeseries",
   "description": "max by pg_stat_activity connection duration on instance level",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (state) (pg_activity_max_conn_duration{instance=\"$instance\", state!=\"idle|disabled\"})",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Backends by Wait Event Type",
   "type": "timeseries",
   "description": "Group by pg_stat_activity.wait_event_type on instance level",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum by (event) (pg_wait_count{instance=\"$instance\"})",
     "legendFormat": "{{ event }}"
    }
   ]
  },
  {
   "title": "Long Lived Xact (Max Xact Lifespan)",
   "type": "timeseries",
   "description": "max by pg_stat_activity transaction duration on instance level",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (state) (pg_activity_max_tx_duration{instance=\"$instance\", state!=\"idle|disabled\"})",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "New Sessions (increase1m)",
   "type": "timeseries",
   "description": "Newly established session on each database.\nIncrease number of last 1 minute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "sum by (datname) (increase(pg_db_sessions{instance=\"$instance\"}[1m]))",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_setting_max_connections{instance=\"$instance\"}",
     "legendFormat": "Max Connection"
    },
    {
     "expr": "pg_setting_max_worker_processes{instance=\"$instance\"}",
     "legendFormat": "Max Worker Process"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 40 },
   "targets": [
    {
     "expr": "sum by (datname) (pg_size_bytes{instance=\"$instance\", datname!~\"wal|log\"})",
     "legendFormat": "Age"
    },
    {
     "expr": "max by (datname) (pg:db:age{instance=\"$instance\"})",
     "legendFormat": "Commit"
    },
    {
     "expr": "max by (datname) (1 - pg_db_is_template{instance=\"$instance\"} + pg_db_allow_conn{instance=\"$primary\"} * 2)",
     "legendFormat": "Status"
    },
    {
     "expr": "sum by (datname) (pg_activity_count{instance=\"$instance\"})",
     "legendFormat": "Session"
    },
    {
     "expr": "sum by (datname) (pg:db:xact_commit_rate1m{instance=\"$instance\"})",
     "legendFormat": "TPS"
    },
    {
     "expr": "max by (datname) (pg_db_conn_limit{instance=\"$instance\"})",
     "legendFormat": "Conn Limit"
    },
    {
     "expr": "max by (datname) (pgbouncer:db:conn_usage{instance=\"$instance\"})",
     "legendFormat": "Pool Usage"
    },
    {
     "expr": "max by (datname) (pg:db:conn_usage{instance=\"$instance\"})",
     "legendFormat": "PG Conn Usage"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_disabled{instance=\"$instance\", datname!=\"pgbouncer\"})",
     "legendFormat": "Disabled"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_paused{instance=\"$instance\", datname!=\"pgbouncer\"})",
     "legendFormat": "Paused"
    }
   ]
  },
  {
   "title": "PG Conn Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:db:conn_usage{instance=\"$instance\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Pgbouncer Conn Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pgbouncer:db:conn_usage{instance=\"$instance\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Session by Database",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum by (datname) (pg_activity_count{instance=\"$instance\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "New Sessions 1m (PG14)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "sum (increase(pg_db_sessions{instance=\"$instance\"}[1m]))",
     "legendFormat": "New Session in Last 1 minute"
    }
   ]
  },
  {
   "title": "Active Backend",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "pg_activity_count{instance=\"$instance\", state=\"active\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "iXact Backend",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "sum by (datname) (pg_activity_count{instance=\"$instance\", state=~\"idle in.*\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  { "title": "Session Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "New Sessions in 1m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "increase(pg_db_sessions{instance=\"$instance\"}[1m])",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Session Failures in 1m",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "increase(pg_db_sessions_abandoned{instance=\"$instance\"}[1m])",
     "legendFormat": "[Abandoned] : {{ datname }}"
    },
    {
     "expr": "increase(pg_db_sessions_fatal{instance=\"$instance\"}[1m])",
     "legendFormat": "[Fatal] : {{ datname }}"
    },
    {
     "expr": "increase(pg_db_sessions_killed{instance=\"$instance\"}[1m])",
     "legendFormat": "[Killed] : {{ datname }}"
    }
   ]
  },
  {
   "title": "Session Time",
   "type": "timeseries",
   "description": "Time spent by database sessions in this database",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pg_db_session_time{instance=\"$instance\"}[1m])",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Active Time",
   "type": "timeseries",
   "description": "Time spent executing SQL statements in this database",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pg_db_active_time{instance=\"$instance\"}[1m])",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Idle in Xact Time",
   "type": "timeseries",
   "description": "Time spent idling while in a transaction in this database",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pg_db_ixact_time{instance=\"$instance\"}[1m])",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Session Time (avg by backend)",
   "type": "timeseries",
   "description": "Time spent by database sessions in this database",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pg_db_session_time{instance=\"$instance\"}[1m]) / on(instance) group_left() pg:instance:num_backends{instance=\"$instance\"}",
     "legendFormat": "{{ datname }}"
    },
    { "expr": "1", "legendFormat": "1" }
   ]
  },
  {
   "title": "Active Time (avg by backend)",
   "type": "timeseries",
   "description": "Time spent executing SQL statements in this database",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pg_db_active_time{instance=\"$instance\"}[1m]) / on(instance) group_left() pg:instance:num_backends{instance=\"$instance\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Idle in Xact Time (avg by backend)",
   "type": "timeseries",
   "description": "Time spent idling while in a transaction in this database",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pg_db_ixact_time{instance=\"$instance\"}[1m]) / on(instance) group_left() pg:instance:num_backends{instance=\"$instance\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Active Ratio (of CPU Time)",
   "type": "timeseries",
   "description": "Time spent executing SQL statements in this database",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(pg_db_active_time{instance=\"$instance\"}[1m]) / on(instance) group_left() sum by (instance)(rate(node_cpu_seconds_total{instance=\"$instance\"}[1m]))",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Active Ratio (of Session Time)",
   "type": "timeseries",
   "description": "Time spent executing SQL statements in this database",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(pg_db_active_time{instance=\"$instance\"}[1m]) / rate(pg_db_session_time{instance=\"$instance\"}[1m])",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Idle in Xact Ratio (of Session Time)",
   "type": "timeseries",
   "description": "Time spent executing SQL statements in this database",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(pg_db_ixact_time{instance=\"$instance\"}[1m]) / rate(pg_db_session_time{instance=\"$instance\"}[1m])",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  { "title": "Pgbouncer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "Databases in Pgbouncer",
   "type": "table",
   "description": "Database in Pgbouncer of this instance ${instance}",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "sum by (datname,host,real_datname) (pgbouncer_database_pool_size{instance=\"$instance\", datname!=\"pgbouncer\"})",
     "legendFormat": "Pool Size"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_reserve_pool{instance=\"$instance\", datname!=\"pgbouncer\"})",
     "legendFormat": "Pool Resv"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_current_connections{instance=\"$instance\", datname!=\"pgbouncer\"})",
     "legendFormat": "Conn"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_max_connections{instance=\"$instance\", datname!=\"pgbouncer\"})",
     "legendFormat": "Conn Max"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_current_connections{instance=\"$instance\", datname!=\"pgbouncer\"}) / sum by (datname) (pgbouncer_database_max_connections{instance=\"$instance\", datname!=\"pgbouncer\"})",
     "legendFormat": "Conn Usage"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_disabled{instance=\"$instance\", datname!=\"pgbouncer\"})",
     "legendFormat": "Disabled"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_paused{instance=\"$instance\", datname!=\"pgbouncer\"})",
     "legendFormat": "Paused"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_server_lifetime{instance=\"$instance\", datname!=\"pgbouncer\"})",
     "legendFormat": "Paused"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 104 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer:instance:pool_databases{instance=\"$instance\"}",
     "legendFormat": "Database"
    },
    {
     "expr": "pgbouncer:instance:pool_users{instance=\"$instance\"}",
     "legendFormat": "User"
    },
    {
     "expr": "pgbouncer:instance:pools{instance=\"$instance\"}",
     "legendFormat": "Pools"
    },
    {
     "expr": "pgbouncer:instance:free_servers{instance=\"$instance\"}",
     "legendFormat": "Free Srv"
    },
    {
     "expr": "pgbouncer:instance:active_servers{instance=\"$instance\"}",
     "legendFormat": "Active Srv"
    },
    {
     "expr": "pgbouncer:instance:active_clients{instance=\"$instance\"}",
     "legendFormat": "Active Clients"
    },
    {
     "expr": "pgbouncer:instance:free_clients{instance=\"$instance\"}",
     "legendFormat": "Free Clients"
    },
    {
     "expr": "pgbouncer:instance:used_clients{instance=\"$instance\"}",
     "legendFormat": "Used Clients"
    },
    {
     "expr": "pgbouncer:instance:login_clients{instance=\"$instance\"}",
     "legendFormat": "Login Clients"
    },
    {
     "expr": "max(pgbouncer:db:conn_usage{instance=\"$instance\"})",
     "legendFormat": "Conn Usage"
    }
   ]
  },
  {
   "title": "Pgbouncer Connection Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pgbouncer:db:conn_usage{instance=\"$instance\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Pgbouncer Servers & Clients",
   "type": "timeseries",
   "description": "New Conn Rate/s in last Minute: Number of assignment for server assigned to client",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 107 },
   "targets": [
    {
     "expr": "-pgbouncer:instance:active_servers{instance=\"$instance\"}-\npgbouncer:instance:idle_servers{instance=\"$instance\"}-\npgbouncer:instance:used_servers{instance=\"$instance\"}-\npgbouncer:instance:tested_servers{instance=\"$instance\"}-\npgbouncer:instance:login_servers{instance=\"$instance\"}\n",
     "legendFormat": "servers"
    },
    {
     "expr": "pgbouncer:instance:active_clients{instance=\"$instance\"}+\npgbouncer:instance:waiting_clients{instance=\"$instance\"}\n",
     "legendFormat": "Clients"
    }
   ]
  },
  {
   "title": "Max Wait",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pgbouncer:pool:maxwait{instance=\"$instance\"}",
     "legendFormat": "{{ user }}@{{ datname }}"
    }
   ]
  },
  {
   "title": "Pgbouncer Server Assignment Rate",
   "type": "timeseries",
   "description": "New Conn Rate/s in last Minute: Number of assignment for server assigned to client",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 114 },
   "targets": [
    {
     "expr": "pgbouncer_stat_avg_server_assignment_count{instance=\"$instance\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Pgbouncer Server State",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 121 },
   "targets": [
    {
     "expr": "pgbouncer:instance:active_servers{instance=\"$instance\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "pgbouncer:instance:used_servers{instance=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "pgbouncer:instance:idle_servers{instance=\"$instance\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "pgbouncer:instance:tested_servers{instance=\"$instance\"}",
     "legendFormat": "Tested"
    },
    {
     "expr": "pgbouncer:instance:login_servers{instance=\"$instance\"}",
     "legendFormat": "Login"
    }
   ]
  },
  {
   "title": "Pgbouncer Client State",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 121 },
   "targets": [
    {
     "expr": "pgbouncer:instance:active_clients{instance=\"$instance\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "pgbouncer:pool:waiting_clients{instance=\"$instance\"}",
     "legendFormat": "Waiting"
    }
   ]
  },
  {
   "title": "Active Server by Database",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 128 },
   "targets": [
    {
     "expr": "pgbouncer:db:active_servers{instance=\"$instance\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Active Clients by Database",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 128 },
   "targets": [
    {
     "expr": "pgbouncer:db:active_clients{instance=\"$instance\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  { "title": "Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 135 } },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 136 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pgbouncer_pool_active_clients{instance=\"$instance\"}",
     "legendFormat": "[{{ pool_mode }}]] {{ user }}@{{ datname }}"
    }
   ]
  },
  {
   "title": "Clients by User",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 136 },
   "targets": [
    {
     "expr": "sum by (user) (pgbouncer:pool:active_clients{instance=\"$instance\"})",
     "legendFormat": "{{ user }}"
    }
   ]
  },
  {
   "title": "Clients by Pool",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 143 },
   "targets": [
    {
     "expr": "pgbouncer:pool:active_clients{instance=\"$instance\"}",
     "legendFormat": "{{ user }}@{{ datname }}"
    }
   ]
  },
  {
   "title": "Clients by Database",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 143 },
   "targets": [
    {
     "expr": "sum by (datname) (pgbouncer:pool:active_clients{instance=\"$instance\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  }
 ]
}