{
 "title": "PGSQL Instance",
 "description": "PostgreSQL Instance Dashboard",
 "tags": [
  "FX",
  "PGSQL",
  "Instance"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "DS_VLOGS",
    "label": "DS (Logs)",
    "query": "victoriametrics-logs-datasource"
   },
   { "name": "DS_VMETRICS", "label": "DS (Metrics)", "query": "prometheus" },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(pg_up, instance)" } },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(pg_up{instance=\"$instance\"} , ip)"
    }
   },
   {
    "name": "seq",
    "label": "Sequence",
    "query": {
     "query": "label_values(pg_up{instance=\"$instance\"},  instance)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(pg_up{instance=\"$instance\"}, cluster)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{ip=\"$ip\"},nodename)"
    }
   },
   {
    "name": "datname",
    "label": "Database",
    "query": {
     "query": "label_values(pg_db_age{instance=\"$instance\",datname!~'template0|template1'}, datname)"
    }
   },
   {
    "name": "node_ins",
    "label": "Node Instance",
    "query": {
     "query": "label_values(node_load1{ip=\"$ip\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Instance",
        "type": "string",
        "values": [ "$instance" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Cluster",
        "type": "string",
        "values": [ "${cluster}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Node IP",
        "type": "string",
        "values": [ "${ip}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Hostname",
        "type": "string",
        "values": [ "${node}" ]
       }
      ],
      "meta": {}
     }
    }
   ]
  },
  {
   "type": "table",
   "description": "All instances among pgsql cluster ${cluster}\n\nInstance: Goto PGSQL Instance\n\nIP: Goto PGSQL Node\n\nStatus: Goto PGSQL Service\n\nLoad: max(cpu,postgres,pgbouncer)\n\nSpace: Disk space usage max(all device)\n\nProxy: session number, Goto Haproxy Admin Page",
   "gridPos": { "h": 6, "w": 14, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "min by (instance,ip) (up{job=\"pgsql\", cluster=\"$cluster\"})"
    },
    {
     "expr": "max by (instance) (pg:instance:load1{cluster=\"$cluster\"})"
    },
    {
     "expr": "sum by (instance) (pg:instance:xact_total_rate1m{cluster=\"$cluster\"})"
    },
    {
     "expr": "min by (instance,ip) (pg_in_recovery{cluster=\"$cluster\"})"
    },
    {
     "expr": "max by (instance) (pg:instance:num_backends{cluster=\"$cluster\"})"
    },
    { "expr": "vector(0)" }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "max by (datname) (pg_db_datid{instance=\"$instance\"})",
     "legendFormat": "OID"
    }
   ]
  },
  {
   "title": "Aliveness",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_up{instance=\"$instance\"}",
     "legendFormat": "postgres"
    },
    {
     "expr": "pgbouncer_up{instance=\"$instance\"}",
     "legendFormat": "pgbouncer"
    },
    { "expr": "vector(0)", "legendFormat": "patroni" },
    {
     "expr": " pg_exporter_agent_up{instance=\"$instance\"}",
     "legendFormat": "pg_exporter"
    },
    {
     "expr": " pgbouncer_exporter_agent_up{instance=\"$instance\"}",
     "legendFormat": "pgb_exporter"
    },
    {
     "expr": " pgbackrest_exporter_agent_up{instance=\"$instance\"}",
     "legendFormat": "pgbackrest"
    },
    {
     "expr": " node_up{ip=~\"$ip\"}",
     "legendFormat": "node"
    }
   ]
  },
  {
   "title": "Postgres",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_up{instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pg_uptime{instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pg_version{instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pg_conf_reload_time{instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pg:instance:timeline{instance=\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "pg_is_wal_replay_paused{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replication",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_in_recovery{instance=\"$instance\"}",
     "legendFormat": "recovery"
    },
    {
     "expr": "(pg_recv_init_lsn{instance=\"$instance\"} > bool 0) or on() vector(0)",
     "legendFormat": "{{ sender_host }} "
    },
    { "expr": "vector(0)", "legendFormat": "Downstream" },
    {
     "expr": "pg_sync_standby_enabled{instance=\"$instance\"}",
     "legendFormat": "Sync Commit"
    },
    {
     "expr": "count by (instance)(pg_pubrel_count{instance=\"$instance\"}) > bool 0 or on() vector(0)",
     "legendFormat": "Publication"
    },
    {
     "expr": "count by (instance)(pg_sub_id{instance=\"$instance\"}) or on() vector(0)",
     "legendFormat": "Subscription"
    }
   ]
  },
  {
   "title": "HA Status",
   "type": "stat",
   "description": "HA Agent - Patroni Metrics",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Service",
   "type": "stat",
   "description": "The number of proxies that serve corresponding service and have route to this ${instance} server.\n\nClick goes to PGSQL Service Dashboard",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "vector(0)", "legendFormat": "{{ proxy }}" }
   ]
  },
  {
   "title": "Database",
   "type": "stat",
   "description": "TPS (1m) of each database on this postgres server",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_db_xact_total{instance=\"$instance\", datname!~'template\\\\d'}[1m]))",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "instance:pressure1{instance=\"$instance\"}",
     "legendFormat": "PG LOAD"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:instance:cpu_usage_1m{ip=\"$ip\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:instance:xact_commit_rate1m{instance=\"$instance\"}",
     "legendFormat": "Commit"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:instance:xact_rollback_rate1m{instance=\"$instance\"}",
     "legendFormat": "Rollback"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:instance:lsn_rate1m{instance=\"$instance\"}",
     "legendFormat": "LSN Rate"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without(datname) (pg_db_numbackends{instance=\"$instance\"}) / pg_setting_max_connections{instance=\"$instance\"}",
     "legendFormat": "Conn%"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (cluster,instance)(pg_replication_lag_seconds{instance=\"$instance\"} or pg_lag{instance=\"$instance\"} or vector(0))",
     "legendFormat": "Lag"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node:fs:space_usage{ip=\"$ip\"}",
     "legendFormat": "Space: {{ mountpoint }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:cluster:load1{cluster=\"$cluster\"}",
     "legendFormat": "Postgres"
    },
    {
     "expr": "pgbouncer:cluster:load1{cluster=\"$cluster\"}",
     "legendFormat": "Pgbouncer"
    },
    {
     "expr": "sum(rate(process_cpu_seconds_total{cluster=\"$cluster\"}[1m]))",
     "legendFormat": "Exporter"
    },
    { "expr": "vector(0)", "legendFormat": "Haproxy" },
    {
     "expr": "pg:cluster:cpu_usage{cluster=\"$cluster\"}",
     "legendFormat": "Node"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Overall pressure for this PostgreSQL Node and Instance. \nmax(node:instance:cpu_usage, pg:instance:load, pgbouncer:instance:load)",
   "gridPos": { "h": 5, "w": 9, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:instance:load1{instance=\"$instance\"}",
     "legendFormat": "p1"
    },
    {
     "expr": "pg:instance:load5{instance=\"$instance\"}",
     "legendFormat": "p5"
    },
    {
     "expr": "pg:instance:load15{instance=\"$instance\"}",
     "legendFormat": "p15"
    }
   ]
  },
  {
   "type": "timeseries",
   "description": "Alerting event graph. Each stripe represents an alerting event. Gray transparent stripes are pending alerts.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ALERTS{instance=\"$instance\", alertstate=\"firing\"}",
     "legendFormat": "[{{ severity }}🔥] {{alertname}}"
    },
    {
     "expr": "ALERTS{instance=\"$instance\", alertstate=\"pending\"} ",
     "legendFormat": "[{{ severity }}⏰] {{alertname}}"
    }
   ]
  },
  { "title": "Member", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_meta_info{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Database",
   "type": "table",
   "description": "Database of this cluster ${cluster}\n\nLoad: active_time / backends (PG14 only)\n\nQuery RT : max query rt of this database\n\nClient: Pgbouncer Active Clients\n\nServer: Pgbouncer Active Servers\n\nBackend: Postgres num backends\n\nT = is Template?\n\nD = Disabled in Pgbouncer ?\n\nP = Paused in Pgbouncer ?",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by (datname) (pg_size_bytes{cluster=\"$cluster\", datname!~\"wal|log\"})",
     "legendFormat": "Size"
    },
    {
     "expr": "max by (datname) (pg:db:age{cluster=\"$cluster\"})",
     "legendFormat": "Age"
    },
    {
     "expr": "max by (datname) (pg_db_is_template{cluster=\"$cluster\", instance=\"$primary\"})",
     "legendFormat": "isTemplate"
    },
    {
     "expr": "sum by (datname) (pg_activity_count{cluster=\"$cluster\"})",
     "legendFormat": "Backend"
    },
    {
     "expr": "sum by (datname) (pg:db:xact_commit_rate1m{cluster=\"$cluster\"})",
     "legendFormat": "TPS"
    },
    {
     "expr": "max by (datname) (pg_db_conn_limit{instance=\"$primary\"})",
     "legendFormat": "Conn Limit"
    },
    {
     "expr": "max by (datname) (pgbouncer:db:query_rt_1m{instance=\"$primary\"})",
     "legendFormat": "RT"
    },
    {
     "expr": "max by (datname) (pg:db:conn_usage{cluster=\"$cluster\"})",
     "legendFormat": "PG Conn Usage"
    },
    {
     "expr": "max by (datname) (pgbouncer_database_disabled{instance=\"$primary\", datname!=\"pgbouncer\"})",
     "legendFormat": "Disabled"
    },
    {
     "expr": "max by (datname) (pgbouncer_database_paused{instance=\"$primary\", datname!=\"pgbouncer\"})",
     "legendFormat": "Paused"
    },
    {
     "expr": "sum by (datname) (pg:db:active_time_rate1m{cluster=\"$cluster\"}) / sum by (datname) (pg_db_numbackends{cluster=\"$cluster\"})",
     "legendFormat": "Load"
    },
    {
     "expr": "sum by (datname) (pgbouncer:db:active_clients{cluster=\"$cluster\"})",
     "legendFormat": "Client"
    },
    {
     "expr": "sum by (datname) (pgbouncer:db:active_servers{cluster=\"$cluster\"})",
     "legendFormat": "Server"
    },
    {
     "expr": "max by (datname,host) (pgbouncer_database_pool_size{cluster=\"$cluster\", datname!=\"pgbouncer\"} + pgbouncer_database_reserve_pool{cluster=\"$cluster\", datname!=\"pgbouncer\"})",
     "legendFormat": "PoolSize"
    },
    {
     "expr": "max by (datname) (pg_db_datid{cluster=\"$cluster\"})",
     "legendFormat": "OID"
    }
   ]
  },
  {
   "type": "stat",
   "description": "Blue = PostgreSQL\n\nGreen = Pgbouncer\n\nYellow = Agent (Patroni / PG Exporters)",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_up{ip=\"$ip\"}",
     "legendFormat": "postgres {{ instance }}"
    },
    {
     "expr": "pgbouncer_up{ip=\"$ip\"}",
     "legendFormat": "pgbouncer {{ instance }}"
    },
    { "expr": "vector(0)", "legendFormat": "patroni {{ instance }}" },
    {
     "expr": "pg_exporter_agent_up{ip=\"$ip\"}",
     "legendFormat": "pg_exporter {{ instance }}"
    },
    {
     "expr": "pgbouncer_exporter_agent_up{ip=\"$ip\"}",
     "legendFormat": "pgb_exporter {{ instance }}"
    },
    {
     "expr": "node_up{ip=\"$ip\"}",
     "legendFormat": "node {{ instance }}"
    },
    { "expr": "vector(0)", "legendFormat": "haproxy {{ instance }}" },
    {
     "expr": "docker_up{ip=\"$ip\"}",
     "legendFormat": "docker {{ instance }}"
    },
    {
     "expr": "vector_up{ip=\"$ip\"}",
     "legendFormat": "vector {{ instance }}"
    },
    {
     "expr": "max by (instance) (up{job=\"juice\", ip=\"$ip\"})",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "max by (instance) (up{cluster=\"nginx\", ip=\"$ip\"})",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "max by (instance) (up{cluster=\"grafana\", ip=\"$ip\"})",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "max by (instance) (up{cluster=\"vmetrics\", ip=\"$ip\"})",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "max by (instance) (up{cluster=\"vlogs\", ip=\"$ip\"})",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "max by (instance) (up{cluster=\"vtraces\", ip=\"$ip\"})",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "max by (instance) (up{cluster=\"vmalert\", ip=\"$ip\"})",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "max by (instance) (up{cluster=\"alertmanager\", ip=\"$ip\"})",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "etcd_up{ip=\"$ip\"}",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "redis_up{ip=\"$ip\"}",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "minio_up{ip=\"$ip\"}",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "mongo_up{ip=\"$ip\"}",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "mysql_up{ip=\"$ip\"}",
     "legendFormat": "mysql {{ instance }}"
    },
    {
     "expr": "mysql_exporter_up{ip=\"$ip\"}",
     "legendFormat": "mysql_exporter"
    }
   ]
  },
  {
   "title": "Patroni Members",
   "type": "table",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 32 },
   "targets": [
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Configuration",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_meta_info{instance=\"$instance\"}"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "CPU Core Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(node:instance:cpu_usage_1m{ip=\"$ip\"}[1m])",
     "legendFormat": "CPU {{ cpu }}"
    }
   ]
  },
  {
   "title": "Replication Lag in Seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(pg_replication_lag_seconds{cluster=\"$cluster\"}) or vector(0)",
     "legendFormat": "upstream's View"
    },
    {
     "expr": "pg_lag{instance=\"$instance\"}",
     "legendFormat": "{{ instance }}'s View"
    }
   ]
  },
  {
   "title": "RT",
   "type": "timeseries",
   "description": "Average transaction response time from Pgbouncer.\nYou can use PostgreSQL metric after PG14",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "#pgbouncer:instance:xact_rt_1m{instance=\"$instance\"}\npg:instance:active_time_rate1m{instance=\"$instance\"} / pg:instance:xact_total_rate1m{instance=\"$instance\"} # PG14",
     "legendFormat": "instance"
    },
    {
     "expr": "# pgbouncer:db:xact_rt_1m{instance=\"$instance\"}\npg:db:active_time_rate1m{instance=\"$instance\", datname!~'template\\\\d'} / pg:db:xact_total_rate1m{instance=\"$instance\", datname!~'template\\\\d'} # PG14",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Session",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "pg_db_numbackends{instance=\"$instance\", datname!~'template\\\\d'}",
     "legendFormat": "client backend @ {{ datname }}"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "description": "Transactions per seconds for each database in Last 5 minutes",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_db_xact_total{instance=\"$instance\",datname!~\"template[0-9]\"}[5m])",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "CRUD",
   "type": "timeseries",
   "description": "Tuples fetched, inserted, updated, delete among this cluster",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(pg_db_tup_fetched{instance=\"$instance\"}[1m]))",
     "legendFormat": "SELECT"
    },
    {
     "expr": "sum(rate(pg_db_tup_inserted{instance=\"$instance\"}[1m]))",
     "legendFormat": "INSERTED"
    },
    {
     "expr": "sum(rate(pg_db_tup_updated{instance=\"$instance\"}[1m]))",
     "legendFormat": "UPDATED"
    },
    {
     "expr": "sum(rate(pg_db_tup_deleted{instance=\"$instance\"}[1m]))",
     "legendFormat": "DELETED"
    }
   ]
  },
  {
   "title": "Statements RT",
   "type": "timeseries",
   "description": "Time spent per second for each query of each instances.",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pg_query_exec_time{instance=\"$instance\"}[5m])",
     "legendFormat": "{{ datname }}-{{ query }}"
    }
   ]
  },
  {
   "title": "Disk / Network",
   "type": "timeseries",
   "description": "R▲ for disk read bandwidth\nTX▲ for network transmit bandwidth\nRX▼ for network receive bandwidth\nW▼ for disk write bandwidth",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "node:instance:disk_read_bytes_rate1m{ip=\"$ip\"}",
     "legendFormat": "{{ device }}-R▲"
    },
    {
     "expr": "node:instance:network_tx_bytes_rate1m{ip=\"$ip\"}",
     "legendFormat": "{{ device }}-TX▲"
    },
    {
     "expr": "- node:instance:network_rx_bytes_rate1m{ip=\"$ip\"}",
     "legendFormat": "{{ device }}-RX▼"
    },
    {
     "expr": "- node:instance:disk_write_bytes_rate1m{ip=\"$ip\"}",
     "legendFormat": "{{ device }}-W▼"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "PG Logs",
   "type": "timeseries",
   "description": "PGSQL Logs Event",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "host:$instance service_name:timescaledb | stats count() as count",
     "legendFormat": "postgres"
    },
    {
     "expr": "host:$instance\nservice_name:in(\"timescaledb\",\"pgcat\") \n| stats by (service_name) count() as count",
     "legendFormat": "{{ app }}"
    }
   ]
  },
  {
   "title": "PostgreSQL Logs",
   "type": "logs",
   "description": "Recent logs for PGSQL components: postgres & patroni & pgbouncer & pgbackrest & exporters & vip-manager",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "host:$instance service_name:timescaledb"
    }
   ]
  }
 ]
}