{
 "title": "PGSQL Tables",
 "description": "PGSQL Tables overview of single database",
 "tags": [
  "FX",
  "PGSQL",
  "Database"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_VMETRICS", "label": "DS (Metrics)", "query": "prometheus" },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(pg_up, instance)" } },
   {
    "name": "datname",
    "label": "Database",
    "query": {
     "query": "label_values(pg_db_age{instance=\"$instance\"}, datname)"
    }
   },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(pg_up{instance=\"$instance\"} , instance)"
    }
   },
   {
    "name": "seq",
    "label": "Sequence",
    "query": {
     "query": "label_values(pg_up{instance=\"$instance\"},  instance)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(pg_up{instance=\"$instance\"}, cluster)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{instance=\"$instance\"}, nodename)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Database",
        "type": "string",
        "values": [ "${datname}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Instance",
        "type": "string",
        "values": [ "$instance" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Cluster",
        "type": "string",
        "values": [ "${cluster}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 13, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "min by (instance,ip) (up{job=\"pgsql\", cluster=\"$cluster\"})"
    },
    {
     "expr": "max by (instance) (pg:instance:load1{cluster=\"$cluster\"})"
    },
    {
     "expr": "sum by (instance) (pg:instance:xact_total_rate1m{cluster=\"$cluster\"})"
    },
    {
     "expr": "min by (instance,ip) (pg_in_recovery{cluster=\"$cluster\"})"
    },
    {
     "expr": "max by (instance) (pg:instance:num_backends{cluster=\"$cluster\"})"
    },
    {
     "expr": "max by (instance) (pgbouncer:instance:xact_rt_1m{cluster=\"$cluster\"})"
    },
    {
     "expr": "sum by (instance) (haproxy_backend_current_sessions{cluster=\"$cluster\", proxy!=\"stats\"})"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "expr": "max by (datname) (pg_db_datid{instance=\"$instance\"})",
     "legendFormat": "OID"
    }
   ]
  },
  {
   "title": "Tables",
   "type": "table",
   "description": "`pg_class` and `pg_stat_user_tables` metrics",
   "gridPos": { "h": 14, "w": 14, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "max by (relname, relid) (pg_table_relid{instance=\"$instance\"})",
     "legendFormat": "OID"
    },
    {
     "expr": "max by (relname) (pg_table_size_bytes{instance=\"$instance\", datname=\"$datname\"})",
     "legendFormat": "Table Size"
    },
    {
     "expr": "sum by (relname) (pg:table:scan_rate1m{instance=\"$instance\", datname=\"$datname\"})",
     "legendFormat": "Table Scan"
    },
    {
     "expr": "sum by (relname) (pg_table_seq_scan{instance=\"$instance\", datname=\"$datname\"})",
     "legendFormat": "Seq Scan"
    },
    {
     "expr": "sum by (relname) (rate(pg_table_tup_read{instance=\"$instance\", datname=\"$datname\"}[1m]))",
     "legendFormat": "Tup Read"
    },
    {
     "expr": "sum by (relname) (rate(pg_table_n_tup_mod{instance=\"$instance\", datname=\"$datname\"}[1m]))",
     "legendFormat": "Tup Mod"
    },
    {
     "expr": "max by (relname) (pg_table_n_live_tup{instance=\"$instance\", datname=\"$datname\"})",
     "legendFormat": "Tup Live"
    },
    {
     "expr": "max by (relname) (pg_table_n_dead_tup{instance=\"$instance\", datname=\"$datname\"})",
     "legendFormat": "Tup Dead"
    },
    {
     "expr": "max by (relname) (pg_table_n_dead_tup{instance=\"$instance\", datname=\"$datname\"} / \n(pg_table_n_live_tup{instance=\"$primary\", datname=\"$datname\"} + pg_table_n_dead_tup{instance=\"$primary\", datname=\"$datname\"}))",
     "legendFormat": "Dead%"
    }
   ]
  },
  {
   "title": "Table Size & Access",
   "type": "marcusolsson-treemap-panel",
   "description": "Index Scan + Seq Scan on this table per second.\n\nSize by table size, Color by table scan rate.",
   "gridPos": { "h": 14, "w": 10, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (relname) (pg_table_size_bytes{cluster=\"$cluster\", datname=\"$datname\"})",
     "legendFormat": "{{ relname }}"
    },
    {
     "expr": "sum by (relname) (\n    pg:table:scan_rate1m{cluster=\"$cluster\", datname=\"$datname\"}\n)",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Table Scan (scan/s)",
   "type": "timeseries",
   "description": "Index Scan + Seq Scan on this table per second",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (relname) (\n    pg:table:scan_rate1m{cluster=\"$cluster\", datname=\"$datname\"}\n)",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Tuple Read (rows/s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (relname) (\n    rate(pg_table_tup_read{cluster=\"$cluster\", datname=\"$datname\"}[1m])\n)",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  { "title": "Table Scan", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Index Scan",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_idx_scan{instance=\"$instance\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Sequential Scan",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(pg_table_seq_scan{instance=\"$instance\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Index Scan -- Scanned Tuples",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_idx_tup_fetch{instance=\"$instance\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Sequential Scan -- Scanned Tuples",
   "type": "timeseries",
   "description": "Rate of tuples been sequential scanned",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_seq_tup_read{instance=\"$instance\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Index Scan -- Rows per Scan",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_idx_tup_fetch{instance=\"$instance\", datname=\"$datname\"}[1m]) / rate(pg_table_idx_scan{instance=\"$instance\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Total Scanned Tuples",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_idx_tup_fetch{instance=\"$instance\", datname=\"$datname\"}[1m]) + rate(pg_table_seq_tup_read{instance=\"$instance\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  { "title": "Table Modify", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Inserted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_n_tup_ins{instance=\"$instance\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Deleted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_n_tup_del{instance=\"$instance\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Updated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_n_tup_upd{instance=\"$instance\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "HOT Updated Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(pg_table_n_tup_hot_upd{instance=\"$instance\", datname=\"$datname\"}[1m]) / rate(pg_table_n_tup_upd{instance=\"$instance\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Modified",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_n_tup_mod{instance=\"$instance\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "HOT Updated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_table_n_tup_hot_upd{instance=\"$instance\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  { "title": "Table Tuple", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Live Tuple",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_table_n_live_tup{instance=\"$instance\", datname=\"$datname\"}",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Dead Tuple",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_table_n_dead_tup{instance=\"$instance\", datname=\"$datname\"}",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Live Tuple Delta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(pg_table_n_live_tup{instance=\"$instance\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  {
   "title": "Dead Tuple Delta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(pg_table_n_dead_tup{instance=\"$instance\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ relname }}"
    }
   ]
  },
  { "title": "Index Access", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "Index Access",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_index_idx_scan{instance=\"$instance\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ idxname }}"
    }
   ]
  },
  {
   "title": "Index Blocks Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(pg_index_idx_blks_hit{instance=\"$instance\", datname=\"$datname\"}[1m]) / (rate(pg_index_idx_blks_read{instance=\"$instance\", datname=\"$datname\"}[1m]) + rate(pg_index_idx_blks_hit{instance=\"$instance\", datname=\"$datname\"}[1m]))",
     "legendFormat": "{{ idxname }}"
    }
   ]
  },
  {
   "title": "Index Entries Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_index_idx_tup_read{instance=\"$instance\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ idxname }}"
    }
   ]
  },
  {
   "title": "Indexed Tuples Fetched",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_index_idx_tup_fetch{instance=\"$instance\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ idxname }}"
    }
   ]
  },
  {
   "title": "Index Entries Read per Scan",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_index_idx_tup_read{instance=\"$instance\", datname=\"$datname\"}[1m]) / rate(pg_index_idx_scan{instance=\"$instance\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ idxname }}"
    }
   ]
  },
  {
   "title": "Indexed Tuples Fetched per Scan",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_index_idx_tup_fetch{instance=\"$instance\", datname=\"$datname\"}[1m])  / rate(pg_index_idx_scan{instance=\"$instance\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ idxname }}"
    }
   ]
  },
  { "title": "Functions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 120 } },
  {
   "title": "Function Call",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(pg_func_calls{instance=\"$instance\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ funcname }}"
    }
   ]
  },
  {
   "title": "Function Time Spend (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pg_func_total_time{instance=\"$instance\", datname=\"$datname\"}[1m]) / rate(pg_func_calls{instance=\"$instance\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ funcname }}"
    }
   ]
  },
  {
   "title": "Function Duration (Self Time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pg_func_self_time{instance=\"$instance\", datname=\"$datname\"}[1m]) / rate(pg_func_calls{instance=\"$instance\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ funcname }}"
    }
   ]
  },
  {
   "title": "Function Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(pg_func_total_time{instance=\"$instance\", datname=\"$datname\"}[1m]) / rate(pg_func_calls{instance=\"$instance\", datname=\"$datname\"}[1m])",
     "legendFormat": "{{ funcname }}"
    }
   ]
  },
  {
   "title": "Maintenance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 137 },
   "panels": [
    {
     "title": "Vacuum (1m)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(pg_table_vacuum_count{instance=\"$instance\", datname=\"$datname\"}[1m]) + increase(pg_table_autovacuum_count{instance=\"$instance\", datname=\"$datname\"}[1m])",
       "legendFormat": "{{ relname }}"
      }
     ]
    },
    {
     "title": "Analyze (1m)",
     "type": "timeseries",
     "description": "How many analyze (auto + manual) executed in last 1m on each table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 146 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(pg_table_analyze_count{instance=\"$instance\", datname=\"$datname\"}[1m]) + increase(pg_table_autoanalyze_count{instance=\"$instance\", datname=\"$datname\"}[1m])",
       "legendFormat": "{{ relname }}"
      }
     ]
    }
   ]
  }
 ]
}