{
 "title": "PGSQL Replication",
 "description": "PostgreSQL Replication of Single cluster",
 "tags": [
  "FX",
  "PGSQL",
  "Cluster"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_VMETRICS", "label": "DS (Metrics)", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(pg_up, cluster)" } },
   {
    "name": "primary",
    "label": "Primary",
    "query": {
     "query": "label_values(pg:cluster:leader{cluster=\"$cluster\"}, instance)"
    }
   },
   {
    "name": "members",
    "label": "Primary",
    "query": {
     "query": "label_values(pg_up{cluster=\"$cluster\"}, ip)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Cluster",
        "type": "string",
        "values": [ "${cluster}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Leader",
        "type": "string",
        "values": [ "$primary" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    }
   ]
  },
  {
   "type": "table",
   "description": "All instances among pgsql cluster ${cluster}\n\nInstance: Goto PGSQL Instance\n\nIP: Goto PGSQL Node\n\nStatus: Goto PGSQL Service\n\nLoad: max(cpu,postgres,pgbouncer)\n\nSpace: Disk space usage max(all device)\n\nProxy: session number, Goto Haproxy Admin Page",
   "gridPos": { "h": 5, "w": 18, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "min by (instance,ip) (up{job=\"pgsql\", cluster=\"$cluster\"})"
    },
    {
     "expr": "max by (instance) (pg:instance:load1{cluster=\"$cluster\"})"
    },
    {
     "expr": "sum by (instance) (pg:instance:xact_total_rate1m{cluster=\"$cluster\"})"
    },
    {
     "expr": "min by (instance,ip) (pg_in_recovery{cluster=\"$cluster\"})"
    },
    {
     "expr": "max by (instance) (pg:instance:num_backends{cluster=\"$cluster\"})"
    },
    {
     "expr": "max by (instance) (pgbouncer:instance:xact_rt_1m{cluster=\"$cluster\"})"
    },
    { "expr": "vector(0)" }
   ]
  },
  {
   "type": "table",
   "description": "Replication Status among cluster ${cluster}",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "count by (cluster) (pg_in_recovery{cluster=\"$cluster\"} == 0) or label_replace(vector(0), \"cluster\", \"$cluster\", \"\", \"\")"
    },
    {
     "expr": "count by (cluster) (pg_in_recovery{cluster=\"$cluster\"} == 1) or label_replace(vector(0), \"cluster\", \"$cluster\", \"\", \"\")"
    }
   ]
  },
  {
   "title": "Leadership",
   "type": "timeseries",
   "description": "Leadership shows who is in charge of this cluster ${cluster}",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg:cluster:leader{cluster=\"$cluster\"}",
     "legendFormat": "leader: {{ instance }}"
    }
   ]
  },
  {
   "title": "Replication Slots",
   "type": "table",
   "description": "Replication Slot of cluster $cluster on Primary Instance $primary",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "max by (instance, slot_name, datname) (pg_slot_retained_bytes{cluster=\"$cluster\", instance=\"$primary\"})"
    },
    {
     "expr": "max by (slot_name) (pg_slot_active{cluster=\"$cluster\", instance=\"$primary\"})"
    },
    {
     "expr": "max by (slot_name) (pg_slot_temporary{cluster=\"$cluster\", instance=\"$primary\"})"
    },
    {
     "expr": "max by (slot_name) (pg_slot_wal_status{cluster=\"$cluster\", instance=\"$primary\"})"
    },
    {
     "expr": "max by (slot_name) (pg_slot_restart_lsn{cluster=\"$cluster\", instance=\"$primary\"})"
    }
   ]
  },
  {
   "title": "Timeline",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_timeline_id{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Replication Lag in Bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 14, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(pg_flush_lsn{cluster=\"$cluster\"} - pg_replay_lsn{cluster=\"$cluster\"}) or vector(0)",
     "legendFormat": "{{ instance }} → {{ appname }}@{{ address }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_flush_lsn{cluster=\"$cluster\"} - pg_replay_lsn{cluster=\"$cluster\"}) or vector(0)",
     "legendFormat": "Lag (B)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_replication_lag_seconds{cluster=\"$cluster\"}) or vector(0)",
     "legendFormat": "Lag (s)"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Replication Lag in Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "max(pg_flush_lsn{cluster=\"$cluster\"} - pg_replay_lsn{cluster=\"$cluster\"}) or vector(0)",
     "legendFormat": "{{ instance }} → {{ usename }}:{{ appname }}@{{ address }}"
    }
   ]
  },
  {
   "title": "Replication Lag in Seconds",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(pg_replication_lag_seconds{cluster=\"$cluster\"}) or vector(0)",
     "legendFormat": "{{ instance }} → {{ usename }}:{{ appname }}@{{ address }}"
    }
   ]
  },
  {
   "title": "Replication Lag in Detail",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "vector(0)",
     "legendFormat": "[SENT] {{ instance }} → {{ usename }}:{{ appname }}@{{ address }}"
    },
    {
     "expr": "vector(0)",
     "legendFormat": "[WRITE] {{ instance }} → {{ usename }}:{{ appname }}@{{ address }}"
    },
    {
     "expr": "vector(0)",
     "legendFormat": "[FLUSH] {{ instance }} → {{ usename }}:{{ appname }}@{{ address }}"
    },
    {
     "expr": "vector(0)",
     "legendFormat": "[REPLAY] {{ instance }} → {{ usename }}:{{ appname }}@{{ address }}"
    }
   ]
  },
  {
   "title": "Replication Lag in Seconds (Follower's View)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_lag{cluster=\"$cluster\"}",
     "legendFormat": "→ {{ instance }}"
    }
   ]
  },
  { "title": "LSN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Replication LSN Progress",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "hex" } },
   "targets": [
    {
     "expr": "max(pg_lsn{cluster=\"$cluster\"})",
     "legendFormat": "Current"
    },
    { "expr": "vector(0)", "legendFormat": "replay @ {{ appname }}" },
    { "expr": "vector(0)", "legendFormat": "flush @ {{ appname }}" },
    { "expr": "vector(0)", "legendFormat": "write @ {{ appname }}" },
    {
     "expr": "pg_slot_restart_lsn{cluster=\"$cluster\"}",
     "legendFormat": "slot restart @ {{ slot_name }}"
    }
   ]
  },
  {
   "title": "Checkpoint LSN Progress",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "hex" } },
   "targets": [
    {
     "expr": "max(pg_lsn{cluster=\"$cluster\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "pg_checkpoint_checkpoint_lsn{instance=\"$primary\"}",
     "legendFormat": "Checkpoint Leader $primary"
    },
    {
     "expr": "pg_checkpoint_checkpoint_lsn{cluster=\"$cluster\", instance!=\"$primary\"}",
     "legendFormat": "Checkpoint Follower {{ instance }}"
    },
    {
     "expr": "pg_checkpoint_redo_lsn{cluster=\"$cluster\", instance!=\"$primary\"}",
     "legendFormat": "Redo {{ instance }}"
    }
   ]
  },
  {
   "title": "LSN Progress Rate 1m",
   "type": "timeseries",
   "description": "Rate of lsn in last minute",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "pg:instance:lsn_rate1m{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "XID", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "XMax Progress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_xact_xmax{cluster=\"$cluster\"}",
     "legendFormat": "xmax-{{ instance }}"
    }
   ]
  },
  {
   "title": "Xmin Progress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_xact_xmin{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "XMin Horizon",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(pg_xact_xmax{cluster=\"$cluster\"})",
     "legendFormat": "XMax"
    },
    { "expr": "vector(0)", "legendFormat": "repl: {{ appname }}" },
    {
     "expr": "pg_slot_catalog_xmin{cluster=\"$cluster\"}",
     "legendFormat": "slot: {{ instance }}.{{ slot_name }}"
    }
   ]
  },
  {
   "title": "Xact in Progress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_xact_xnum{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Slot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Slot Retained Bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_slot_retained_bytes{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}.{{ slot_name }}"
    }
   ]
  },
  {
   "title": "Logical",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 },
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 96 },
     "targets": [
      {
       "expr": "max by (subname) (pg_sub_id{instance=\"$primary\"})"
      },
      {
       "expr": "max by (subname) (pg_sub_pid{instance=\"$primary\"})"
      },
      {
       "expr": "max by (subname) (pg_sub_received_lsn{instance=\"$primary\"})"
      },
      {
       "expr": "max by (subname) (pg_sub_reported_lsn{instance=\"$primary\"})"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 100 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "count by (instance)(pg_pubrel_count{instance=\"$primary\"}) > bool 0 or on() vector(0)",
       "legendFormat": "Publication"
      },
      {
       "expr": "count by (instance)(pg_sub_id{instance=\"$primary\"}) or on() vector(0)",
       "legendFormat": "Subscription"
      }
     ]
    },
    {
     "title": "Publication Table Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 3, "y": 100 },
     "targets": [
      {
       "expr": "pg_pubrel_count{instance=\"$primary\"}",
       "legendFormat": "{{ pubname }}"
      }
     ]
    },
    {
     "title": "Subscription Table Count by State",
     "type": "timeseries",
     "description": "i = init , d = data sync , r = ready",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 100 },
     "targets": [
      {
       "expr": "pg_subrel_count{instance=\"$primary\"}",
       "legendFormat": "{{ subname }}.{{ state }}"
      }
     ]
    }
   ]
  }
 ]
}