{
 "title": "PGSQL Overview",
 "description": "PostgreSQL Monitoring HQ",
 "tags": [
  "FX",
  "PGSQL",
  "Overview",
  "HOME"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_VMETRICS", "label": "DS (Metrics)", "query": "prometheus" },
   { "name": "job", "label": "Environment", "query": "pgsql" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 16, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (cluster) (pg_up{job=\"$job\"}))",
     "legendFormat": "Cluster"
    },
    {
     "expr": "count(pg_up{job=\"$job\"})",
     "legendFormat": "Instance"
    },
    { "expr": "vector(0)", "legendFormat": "Service" },
    {
     "expr": "count(count(pg_up{job=\"$job\"}) by (ip))",
     "legendFormat": "Node"
    },
    {
     "expr": "count(max by (cluster,datname) (pg_db_age{job=\"$job\", datname!~'template0|template1'}))",
     "legendFormat": "DB"
    },
    {
     "expr": "sum(pg:cluster:cpu_count{job=\"$job\"})",
     "legendFormat": "Core"
    },
    {
     "expr": "sum(pg:instance:mem_size{job=\"$job\"})",
     "legendFormat": "Mem"
    },
    {
     "expr": "sum(max by (cluster,datname)(pg_size_bytes{datname!~\"log|wal\", job=\"$job\"}))",
     "legendFormat": "Data"
    }
   ]
  },
  {
   "type": "stat",
   "description": "ETCD Health server ratio, and number of Postgres cluster in Failsafe mode",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"etcd\", cluster=\"etcd\"}) by (cluster) /\n count(up{job=\"etcd\", cluster=\"etcd\"}) by (cluster)\nor on() vector(0)",
     "legendFormat": "ETCD Status"
    },
    { "expr": "vector(0)", "legendFormat": "Failsafe Mode" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:env:cpu_usage{job=\"$job\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg:cluster:num_backends{job=\"$job\"})",
     "legendFormat": "Session"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:env:xact_commit_rate1m{job=\"$job\"}",
     "legendFormat": "Commit"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:env:xact_rollback_rate1m{job=\"$job\"}",
     "legendFormat": "Rollback"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg:instance:space_usage{job=\"$job\"})",
     "legendFormat": "Space Max"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg:env:age{job=\"$job\"}",
     "legendFormat": "Age Max"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg:cluster:lag_bytes{job=\"$job\"})",
     "legendFormat": "Lag Max"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg:cluster:ixact_backends{job=\"$job\"})",
     "legendFormat": "iXact Max"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pgbouncer:cluster:waiting_clients{job=\"$job\"})",
     "legendFormat": "Queue Max"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg:instance:conn_usage{job=\"$job\"})",
     "legendFormat": "Conn Max"
    }
   ]
  },
  {
   "title": "Clusters",
   "type": "stat",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "vector(0)", "legendFormat": "{{ cluster }}" },
    {
     "expr": "pg:cluster:xact_commit_rate1m{job=\"pgrds\"}",
     "legendFormat": "{{ cluster }}"
    },
    { "expr": "vector(0)", "legendFormat": "{{ cluster }}" }
   ]
  },
  {
   "title": "Instances",
   "type": "stat",
   "description": "Blue = PostgreSQL\n\nGreen = Pgbouncer\n\nAzure = Patroni\n\nPurple = Postgres Exporter\n\nDeep Purple = Pgbouncer Exporter\n\nGray = Pgbackrest Exporter\n\nOrange = PG VIP",
   "gridPos": { "h": 14, "w": 16, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " min by (instance) (pg_up{job=\"pgsql\"})",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "min by (instance) (pg_up{job=\"pgrds\"})",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": " min by (instance) (pgbouncer_up{job=\"pgsql\"})",
     "legendFormat": "{{ instance }}"
    },
    { "expr": "vector(0)", "legendFormat": "{{ instance }}" },
    {
     "expr": "pg_exporter_up{job=\"pgsql\"}",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "pgbouncer_exporter_up{job=\"pgsql\"}",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "pgbackrest_exporter_agent_up{job=\"pgsql\"}",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "min by (job,cluster,vip) (probe_success{job=\"pgsql-vip\"})",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", job=~\"pgsql|pgrds\"}) or on() vector(0)",
     "legendFormat": "Firing Alert"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\", job=~\"pgsql|pgrds\"}) by (alertname, severity)",
     "legendFormat": "{{ alertname }}"
    }
   ]
  },
  {
   "title": "Firing Alerts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum without (instance,datname) (ALERTS{alertstate=\"firing\", job=~\"pgsql|pgrds\"})",
     "legendFormat": "[{{ severity }}] {{ alertname }} @ {{ cluster }}"
    },
    { "expr": "0", "legendFormat": "Alert" }
   ]
  },
  {
   "title": "Cluster Std Load5",
   "type": "timeseries",
   "description": "PostgreSQL Cluster Load 5\nLoad = active session time / total cpu time, among the cluster, average in last 5 minute",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg:cluster:load5{job=\"$job\"} != -1",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "Instance TPS",
   "type": "timeseries",
   "description": "Transactions committed + rollback per second in last 1 minute for all instances",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg:instance:xact_total_rate5m{job=~\"pgrds\"}",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "pg:instance:xact_total_rate5m{job=~\"pgsql\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "PGSQL Instances",
   "type": "table",
   "description": "All postgresql instances in this FX deployment",
   "gridPos": { "h": 12, "w": 17, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "min by (cluster,instance,ip) (up{job=\"$job\"})"
    },
    {
     "expr": "max by (instance) (pg:instance:load1{job=\"$job\"})"
    },
    {
     "expr": "max by (instance) (pg:instance:space_usage{job=\"$job\"})  / 1073741824"
    },
    {
     "expr": "max by (instance) (pg:instance:cpu_usage{job=\"$job\"})"
    },
    {
     "expr": "max by (instance) (pg:instance:cpu_count{job=\"$job\"})"
    },
    {
     "expr": "min by (instance) (pg_in_recovery{job=\"$job\"})"
    },
    {
     "expr": "max by (instance) (pg:instance:num_backends{job=\"$job\"})"
    },
    {
     "expr": "max by (instance) (pgbouncer:instance:active_clients{job=\"$job\", proxy!=\"stats\"})"
    },
    {
     "expr": "group by (instance,cluster_id,extensions,version,ver_str) (pg_meta_info{job=\"$job\", proxy!=\"stats\"})"
    },
    {
     "expr": "max by (instance) (pg:instance:mem_size{job=\"$job\"}) / 1073741824"
    },
    {
     "expr": "max by (instance) (pg:instance:fs_size{job=\"$job\"}) / 1073741824"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 22, "w": 7, "x": 17, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(0)", "legendFormat": "{{ instance }}" },
    {
     "expr": "min by (instance) (up{job=\"$job\"}) == 0",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Patroni Members",
   "type": "table",
   "description": "Patroni responsible for Postgres HA\n\nDCS Seen: time since last seen etcd\n\nPaused: is in maintenance mode? (auto failover disabled)\n \nRestart: is there any pending config change that requires restart?\n\nFailsafe: in case of DCS failure, the failsafe mode is enabled to avoid split brain\n\nLock: if failsafe is active, the cluster is locked to prevent any failover\n\nPostgres: the status of it's managed Postgres instance",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 46 },
   "targets": [
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" },
    { "expr": "vector(0)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DCS: etcd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 14, "w": 4, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      { "expr": "vector(0)", "legendFormat": "ETCD Health" },
      { "expr": "vector(0)", "legendFormat": "Failsafe Active" }
     ]
    },
    {
     "title": "ETCD Aliveness",
     "type": "state-timeline",
     "description": "etcd is the DCS used by patroni",
     "gridPos": { "h": 7, "w": 13, "x": 4, "y": 57 },
     "targets": [
      { "expr": "vector(0)", "legendFormat": "ETCD Cluster Healthy" },
      {
       "expr": "up{job=\"etcd\", cluster=\"etcd\"}",
       "legendFormat": "{{ instance }} @ {{ ip }}"
      }
     ]
    },
    {
     "title": "DCS Last Seen",
     "type": "stat",
     "description": "How long since patroni the HA agent successfully connect to DCS:etcd.\nMax amoung cluster\n\nvalue larger than 20s needs extra attention",
     "gridPos": { "h": 14, "w": 7, "x": 17, "y": 57 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "vector(0)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Patroni DCS Last Seen",
     "type": "timeseries",
     "description": "Time since patroni last successful connect to DCS:etcd service",
     "gridPos": { "h": 7, "w": 13, "x": 4, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      { "expr": "vector(0)", "legendFormat": "{{ cluster }}" }
     ]
    }
   ]
  },
  {
   "title": "Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "panels": [
    {
     "title": "Service Session",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 58 },
     "targets": [
      { "expr": "vector(0)", "legendFormat": "{{ proxy }}" }
     ]
    },
    {
     "title": "Service Health",
     "type": "state-timeline",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 64 },
     "targets": [
      { "expr": "vector(0)", "legendFormat": "{{ proxy }}" }
     ]
    },
    {
     "type": "stat",
     "description": "Services SLI is measured by Average Service UP time of last 1 day",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "vector(0)", "legendFormat": "{{ proxy }}" }
     ]
    }
   ]
  },
  {
   "title": "Databases",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "panels": [
    {
     "type": "table",
     "description": "Database of this cluster ${cluster}",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "max by (cluster,instance,datname) (pg_size_bytes{datname!~\"wal|log|template\\\\d\"})",
       "legendFormat": "Age"
      },
      {
       "expr": "max by (instance,datname) (pg:db:age{datname!~\"wal|log|template\\\\d\"})",
       "legendFormat": "Commit"
      },
      {
       "expr": "sum by (instance,datname) (pg:db:xact_commit_rate1m{datname!~\"wal|log|template\\\\d\"})",
       "legendFormat": "TPS"
      },
      {
       "expr": "max by (instance,datname) (pg_db_conn_limit{datname!~\"wal|log|template\\\\d\"})",
       "legendFormat": "Conn Limit"
      },
      {
       "expr": "sum by (instance,datname) (pg_db_numbackends{datname!~\"wal|log|template\\\\d\"})",
       "legendFormat": "Conn Limit"
      }
     ]
    }
   ]
  }
 ]
}