{
 "title": "PGSQL Pgbouncer",
 "description": "PostgreSQL Queries for single Instance",
 "tags": [
  "FX",
  "PGSQL",
  "Instance"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_VMETRICS", "label": "DS (Metrics)", "query": "prometheus" },
   {
    "name": "DS_VLOGS",
    "label": "DS (Logs)",
    "query": "victoriametrics-logs-datasource"
   },
   { "name": "instance", "label": "Instance", "query": { "query": "label_values(pg_up, instance)" } },
   {
    "name": "ip",
    "label": "IP",
    "query": {
     "query": "label_values(pg_up{instance=\"$instance\"} , instance)"
    }
   },
   {
    "name": "seq",
    "label": "Sequence",
    "query": {
     "query": "label_values(pg_up{instance=\"$instance\"},  instance)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(pg_up{instance=\"$instance\"}, cluster)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info{instance=\"$instance\"}, nodename)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Instance",
        "type": "string",
        "values": [ "$instance" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Cluster",
        "type": "string",
        "values": [ "${cluster}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Node IP",
        "type": "string",
        "values": [ "${ip}" ]
       }
      ],
      "meta": {},
      "name": ""
     }
    },
    {
     "frame": {
      "fields": [
       {
        "config": {},
        "name": "Hostname",
        "type": "string",
        "values": [ "${node}" ]
       }
      ],
      "meta": {}
     }
    }
   ]
  },
  {
   "title": "Postgres Instances",
   "type": "table",
   "description": "All instances among pgsql cluster ${cluster}\n\nInstance: Goto PGSQL Instance\n\nIP: Goto PGSQL Node\n\nStatus: Goto PGSQL Service\n\nLoad: max(cpu,postgres,pgbouncer)\n\nSpace: Disk space usage max(all device)\n\nProxy: session number, Goto Haproxy Admin Page",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "pg_in_recovery{cluster=\"$cluster\"}"
    },
    {
     "expr": "sum by (instance) (pg:instance:xact_total_rate1m{cluster=\"$cluster\"})"
    },
    {
     "expr": "max by (instance) (pgbouncer:instance:xact_rt_1m{cluster=\"$cluster\"})"
    },
    {
     "expr": "min by (instance) (up{cluster=\"$cluster\", job=\"pgsql\"})"
    }
   ]
  },
  {
   "title": "Databases in Pgbouncer",
   "type": "table",
   "description": "Database in Pgbouncer of this instance ${instance}",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "sum by (datname,host,real_datname) (pgbouncer_database_pool_size{instance=\"$instance\", datname!=\"pgbouncer\"})",
     "legendFormat": "Pool Size"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_reserve_pool{instance=\"$instance\", datname!=\"pgbouncer\"})",
     "legendFormat": "Pool Resv"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_current_connections{instance=\"$instance\", datname!=\"pgbouncer\"})",
     "legendFormat": "Conn"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_max_connections{instance=\"$instance\", datname!=\"pgbouncer\"})",
     "legendFormat": "Conn Max"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_current_connections{instance=\"$instance\", datname!=\"pgbouncer\"}) / sum by (datname) (pgbouncer_database_max_connections{instance=\"$instance\", datname!=\"pgbouncer\"})",
     "legendFormat": "Conn Usage"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_disabled{instance=\"$instance\", datname!=\"pgbouncer\"})",
     "legendFormat": "Disabled"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_paused{instance=\"$instance\", datname!=\"pgbouncer\"})",
     "legendFormat": "Paused"
    },
    {
     "expr": "sum by (datname) (pgbouncer_database_server_lifetime{instance=\"$instance\", datname!=\"pgbouncer\"})",
     "legendFormat": "Paused"
    }
   ]
  },
  {
   "title": "QPS Seasonality",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer:instance:query_rate5m{instance=\"$instance\"}",
     "legendFormat": "QPS"
    },
    {
     "expr": "pgbouncer:instance:query_rate5m{instance=\"$instance\"} OFFSET 1d",
     "legendFormat": "Yesterday"
    },
    {
     "expr": "pgbouncer:instance:query_rate5m{instance=\"$instance\"} OFFSET 2d",
     "legendFormat": "2 Day Ago"
    }
   ]
  },
  {
   "title": "Average Queries per Xact",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer:instance:query_rate1m{instance=\"$instance\"} / pgbouncer:instance:xact_rate1m{instance=\"$instance\"}",
     "legendFormat": "Q"
    }
   ]
  },
  {
   "title": "Long Run Queries",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (state) (pg_activity_max_duration{instance=\"$instance\", state!~\"(idle.*|disabled)\"})",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Average Queries per Commit",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer:instance:query_rate1m{instance=\"$instance\"} / on(instance) group_left() pg:instance:xact_commit_rate1m{instance=\"$instance\"}",
     "legendFormat": "Q"
    }
   ]
  },
  { "title": "QPS / Query RT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "QPS",
   "type": "timeseries",
   "description": "Pgbouncer Queries per second according to last 1m, 5m, 15m",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer:instance:query_rate1m{instance=\"$instance\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pgbouncer:instance:query_rate5m{instance=\"$instance\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pgbouncer:instance:query_rate15m{instance=\"$instance\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "RT",
   "type": "timeseries",
   "description": "Pgbouncer query average response time in last 1m, 5m, 15m",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pgbouncer:instance:query_rt_1m{instance=\"$instance\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "pgbouncer:instance:query_rt_5m{instance=\"$instance\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "pgbouncer:instance:query_rt_15m{instance=\"$instance\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "QPS Divergence",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(avg_over_time(pgbouncer:instance:query_rate1m{instance=\"$instance\"}[5m]) / stddev_over_time(pgbouncer:instance:query_rate1m{instance=\"$instance\"}[5m])) ^ 2",
     "legendFormat": "QPS Divergence"
    }
   ]
  },
  {
   "title": "RT Divergence",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(avg_over_time(pgbouncer:instance:query_rt_1m{instance=\"$instance\"}[5m]) / stddev_over_time(pgbouncer:instance:query_rt_1m{instance=\"$instance\"}[5m])) ^ 2",
     "legendFormat": "RT Divergence"
    }
   ]
  },
  {
   "title": "QPS Distribution",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg_over_time(pgbouncer:instance:query_rate1m{instance=\"$instance\"}[15m]) + 3 * stddev_over_time(pgbouncer:instance:query_rate1m{instance=\"$instance\"}[15m])",
     "legendFormat": "+3σ"
    },
    {
     "expr": "avg_over_time(pgbouncer:instance:query_rate1m{instance=\"$instance\"}[15m]) - 3 * stddev_over_time(pgbouncer:instance:query_rate1m{instance=\"$instance\"}[15m])",
     "legendFormat": "-3σ"
    },
    {
     "expr": "avg_over_time(pgbouncer:instance:query_rate1m{instance=\"$instance\"}[15m]) + stddev_over_time(pgbouncer:instance:query_rate1m{instance=\"$instance\"}[15m])",
     "legendFormat": "+σ"
    },
    {
     "expr": "avg_over_time(pgbouncer:instance:query_rate1m{instance=\"$instance\"}[15m]) - stddev_over_time(pgbouncer:instance:query_rate1m{instance=\"$instance\"}[15m])",
     "legendFormat": "-σ"
    },
    {
     "expr": "avg_over_time(pgbouncer:instance:query_rate1m{instance=\"$instance\"}[15m])",
     "legendFormat": "µ"
    },
    {
     "expr": "pgbouncer:instance:query_rate1m{instance=\"$instance\"}",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "RT Distribution",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(pgbouncer:instance:query_rt_1m{instance=\"$instance\"}[15m]) + 3 * stddev_over_time(pgbouncer:instance:query_rt_1m{instance=\"$instance\"}[15m])",
     "legendFormat": "+3σ"
    },
    {
     "expr": "avg_over_time(pgbouncer:instance:query_rt_1m{instance=\"$instance\"}[15m]) - 3 * stddev_over_time(pgbouncer:instance:query_rt_1m{instance=\"$instance\"}[15m]) ",
     "legendFormat": "-3σ"
    },
    {
     "expr": "avg_over_time(pgbouncer:instance:query_rt_1m{instance=\"$instance\"}[15m]) + stddev_over_time(pgbouncer:instance:query_rt_1m{instance=\"$instance\"}[15m])",
     "legendFormat": "+σ"
    },
    {
     "expr": "avg_over_time(pgbouncer:instance:query_rt_1m{instance=\"$instance\"}[15m]) - stddev_over_time(pgbouncer:instance:query_rt_1m{instance=\"$instance\"}[15m])",
     "legendFormat": "-σ"
    },
    {
     "expr": "avg_over_time(pgbouncer:instance:query_rt_1m{instance=\"$instance\"}[15m])",
     "legendFormat": "µ"
    },
    {
     "expr": "pgbouncer:instance:query_rt_1m{instance=\"$instance\"}",
     "legendFormat": "v"
    }
   ]
  },
  {
   "title": "QPS by Database",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer:instance:query_rate5m{instance=\"$instance\"}",
     "legendFormat": "Instance"
    },
    {
     "expr": "pgbouncer:db:query_rate5m{instance=\"$instance\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "QPS by Instance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pgbouncer:cluster:query_rate5m{cluster=\"$cluster\"}",
     "legendFormat": "Cluster"
    },
    {
     "expr": "pgbouncer:instance:query_rate5m{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Query RT by Database",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pgbouncer:instance:query_rt_1m{instance=\"$instance\"}",
     "legendFormat": "Instance"
    },
    {
     "expr": "pgbouncer:db:query_rt_1m{instance=\"$instance\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Query RT by Instance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pgbouncer:cluster:query_rt_1m{cluster=\"$cluster\"}",
     "legendFormat": "Cluster"
    },
    {
     "expr": "pgbouncer:instance:query_rt_1m{cluster=\"$cluster\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Session", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 65 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pgbouncer:instance:pool_databases{instance=\"$instance\"}",
     "legendFormat": "Database"
    },
    {
     "expr": "pgbouncer:instance:pool_users{instance=\"$instance\"}",
     "legendFormat": "User"
    },
    {
     "expr": "pgbouncer:instance:pools{instance=\"$instance\"}",
     "legendFormat": "Pools"
    },
    {
     "expr": "pgbouncer:instance:free_servers{instance=\"$instance\"}",
     "legendFormat": "Free Srv"
    },
    {
     "expr": "pgbouncer:instance:active_servers{instance=\"$instance\"}",
     "legendFormat": "Active Srv"
    },
    {
     "expr": "pgbouncer:instance:active_clients{instance=\"$instance\"}",
     "legendFormat": "Active Clients"
    },
    {
     "expr": "pgbouncer:instance:free_clients{instance=\"$instance\"}",
     "legendFormat": "Free Clients"
    },
    {
     "expr": "pgbouncer:instance:used_clients{instance=\"$instance\"}",
     "legendFormat": "Used Clients"
    },
    {
     "expr": "pgbouncer:instance:login_clients{instance=\"$instance\"}",
     "legendFormat": "Login Clients"
    },
    {
     "expr": "max(pgbouncer:db:conn_usage{instance=\"$instance\"})",
     "legendFormat": "Conn Usage"
    }
   ]
  },
  {
   "title": "Pgbouncer Connection Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pgbouncer:db:conn_usage{instance=\"$instance\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Pgbouncer Servers & Clients",
   "type": "timeseries",
   "description": "New Conn Rate/s in last Minute: Number of assignment for server assigned to client",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "-pgbouncer:instance:active_servers{instance=\"$instance\"}-\npgbouncer:instance:idle_servers{instance=\"$instance\"}-\npgbouncer:instance:used_servers{instance=\"$instance\"}-\npgbouncer:instance:tested_servers{instance=\"$instance\"}-\npgbouncer:instance:login_servers{instance=\"$instance\"}\n",
     "legendFormat": "servers"
    },
    {
     "expr": "pgbouncer:instance:active_clients{instance=\"$instance\"}+\npgbouncer:instance:waiting_clients{instance=\"$instance\"}\n",
     "legendFormat": "Clients"
    }
   ]
  },
  {
   "title": "Server Assignment Rate",
   "type": "timeseries",
   "description": "New Conn Rate/s in last Minute: Number of assignment for server assigned to client",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "pgbouncer_stat_avg_server_assignment_count{instance=\"$instance\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Max Wait",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pgbouncer:pool:maxwait{instance=\"$instance\"}",
     "legendFormat": "{{ user }}@{{ datname }}"
    }
   ]
  },
  {
   "title": "Pgbouncer Server State",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "pgbouncer:instance:active_servers{instance=\"$instance\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "pgbouncer:instance:used_servers{instance=\"$instance\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "pgbouncer:instance:idle_servers{instance=\"$instance\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "pgbouncer:instance:tested_servers{instance=\"$instance\"}",
     "legendFormat": "Tested"
    },
    {
     "expr": "pgbouncer:instance:login_servers{instance=\"$instance\"}",
     "legendFormat": "Login"
    }
   ]
  },
  {
   "title": "Pgbouncer Client State",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "expr": "pgbouncer:instance:active_clients{instance=\"$instance\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "pgbouncer:pool:waiting_clients{instance=\"$instance\"}",
     "legendFormat": "Waiting"
    }
   ]
  },
  {
   "title": "Active Server by Database",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "pgbouncer:db:active_servers{instance=\"$instance\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Active Clients by Database",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 89 },
   "targets": [
    {
     "expr": "pgbouncer:db:active_clients{instance=\"$instance\"}",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  { "title": "Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 97 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pgbouncer_pool_active_clients{instance=\"$instance\"}",
     "legendFormat": "[{{ pool_mode }}]] {{ user }}@{{ datname }}"
    }
   ]
  },
  {
   "title": "Clients by User",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 97 },
   "targets": [
    {
     "expr": "sum by (user) (pgbouncer:pool:active_clients{instance=\"$instance\"})",
     "legendFormat": "{{ user }}"
    }
   ]
  },
  {
   "title": "Clients by Pool",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "pgbouncer:pool:active_clients{instance=\"$instance\"}",
     "legendFormat": "{{ user }}@{{ datname }}"
    }
   ]
  },
  {
   "title": "Clients by Database",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 104 },
   "targets": [
    {
     "expr": "sum by (datname) (pgbouncer:pool:active_clients{instance=\"$instance\"})",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  { "title": "Pgbouncer Logs: ${instance}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 } },
  {
   "title": "Pgbouncer Logs",
   "type": "timeseries",
   "description": "Pgbouncer Logs Count",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "host:$instance service_name:pgbouncer | stats count() as count",
     "legendFormat": "pgbouncer"
    }
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 117 },
   "targets": [
    {
     "expr": "host:$instance service_name:pgbouncer"
    }
   ]
  }
 ]
}