name: yai-node-exporter

services:
  node-exporter:
    image: prom/node-exporter:${NODE_EXPORTER_VERSION:-v1.11.1}
    container_name: yai-node-exporter
    restart: unless-stopped
    pid: host
    command:
      - --path.procfs=/host/proc
      - --path.rootfs=/rootfs
      - --path.sysfs=/host/sys
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - yai-infra

networks:
  yai-infra:
    external: true
