{
 "title": "Service Logs",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "DS_VLOGS",
    "label": "DS (Logs)",
    "query": "victoriametrics-logs-datasource"
   },
   { "name": "search", "label": "Search", "query": "*" },
   { "name": "job", "label": "service", "query": { "query": "" } },
   { "name": "node", "label": "stream_type", "query": { "query": "" } },
   { "name": "stream", "label": "service", "query": { "query": "" } }
  ]
 },
 "panels": [
  {
   "title": "Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "service_name:~\"${job:pipe}\" AND stream:~\"${node:pipe}\" AND $search | stats by (_time:$__interval) count() as count"
    }
   ]
  },
  {
   "title": "Logs by job",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "service_name:~\"${job:pipe}\" AND stream:~\"${node:pipe}\" AND $search | stats by (_time:$__interval, service_name) count() as count",
     "legendFormat": "{{nomad_job_name}}"
    }
   ]
  },
  {
   "title": "Logs by level",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "service_name:~\"${job:pipe}\" AND stream:~\"${node:pipe}\" AND $search | stats by (_time:$__interval, level) count() as count",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "service_name:~\"${job:pipe}\" AND stream:~\"${node:pipe}\" AND $search"
    }
   ]
  }
 ]
}