{
 "title": "Qdrant",
 "description": "Basic dashboard for Qdrant DB",
 "tags": [
  "Qdrant",
  "gRPC",
  "REST",
  "DB"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_VMETRICS", "label": "DS (Metrics)", "query": "prometheus" },
   {
    "name": "DS_VLOGS",
    "label": "DS (Logs)",
    "query": "victoriametrics-logs-datasource"
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Qdrant status",
   "type": "stat",
   "description": "Displays if qdrant is up or down",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"qdrant\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gRPC Error rate",
   "type": "stat",
   "description": "Shows how many requests fail over the total",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(grpc_responses_fail_total{endpoint=\"/qdrant.Points/Query\"}[1m])) / \nsum(rate(grpc_responses_total{endpoint=\"/qdrant.Points/Query\"}[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "stat",
   "description": "Displays if the Qdrant is in recovery mode and if its in cluster",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_status_recovery_mode{job=\"qdrant\"}",
     "legendFormat": "Recovery mode"
    },
    {
     "expr": "cluster_enabled{job=\"qdrant\"}\n",
     "legendFormat": "Cluster mode"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "Version of Qdrant instance",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_info{job=\"qdrant\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Collections statistics",
   "type": "stat",
   "description": "Shows number of collections and total number of vectors",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "collections_total", "legendFormat": "__auto" },
    { "expr": "collections_vector_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Overview",
   "type": "stat",
   "description": "Overview of memory usage of Qdrant instance",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_allocated_bytes / 1024 / 1024",
     "legendFormat": "Allocated bytes"
    },
    {
     "expr": "memory_resident_bytes / 1024 / 1024\n",
     "legendFormat": "Resident bytes"
    },
    {
     "expr": "memory_active_bytes / 1024 / 1024\n",
     "legendFormat": "Active bytes"
    }
   ]
  },
  { "title": "gRPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "gRPC response duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(grpc_responses_avg_duration_seconds{endpoint=\"/qdrant.Points/Query\"}) by (endpoint)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(grpc_responses_max_duration_seconds{endpoint=\"/qdrant.Points/Query\"}) by (endpoint)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "min(grpc_responses_min_duration_seconds{endpoint=\"/qdrant.Points/Query\"}) by (endpoint)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gRPC response throughput",
   "type": "timeseries",
   "description": "Number of requests on /Query endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(grpc_responses_total{endpoint=\"/qdrant.Points/Query\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "REST", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "REST response duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(rest_responses_avg_duration_seconds) by (endpoint)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(rest_responses_max_duration_seconds) by (endpoint)\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "min(rest_responses_min_duration_seconds) by (endpoint)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "REST response throughput",
   "type": "timeseries",
   "description": "Number of requests on /Query endpoint",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "rate(rest_responses_total[1m])", "legendFormat": "__auto" }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "type": "logs",
   "description": "Qdrant logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"qdrant\"} |= ``"
    }
   ]
  }
 ]
}